export const beauty = [
    ['Kumkumadi Lepam', 'कुंकुमदि लेपम', ['Acne', 'Glow', 'Dark Spots'], 'External', 'Night Apply', 'चेहरे पर लगाएं'],
    ['Nalpamaradi Keram', 'नालपामरादि केरम', ['Tan Removal', 'Itching', 'Brightening'], 'External', 'Pre-bath', 'नहाने से पहले लगाएं'],
    ['Chemparuthyadi Keram', 'चेम्परुथ्यादि केरम', ['Hair Health', 'Dandruff', 'Scalp Itch'], 'External', 'Hair Oil', 'सिर में लगाएं'],
    ['Durdhuradi Tailam', 'धुधुरादि तैलम', ['Dandruff', 'Itching Scalp', 'Lice'], 'External', 'Hair Oil', 'सिर में लगाएं'],
    ['Kayyanyadi Tailam', 'कय्यन्यादि तैलम', ['Greying Hair', 'Hair Fall', 'Cooling'], 'External', 'Hair Oil', 'सिर में लगाएं'],
    ['Kuntalkanti Tailam', 'कुन्तलकांति तैलम', ['Hair Shine', 'Growth', 'Strength'], 'External', 'Hair Oil', 'सिर में लगाएं'],
    ['Triphaladi Tailam', 'त्रिफलादि तैलम', ['Sinus', 'Hair', 'Headache'], 'External', 'Head Massage', 'सिर की मालिश'],
    ['Chandanadi Tailam', 'चंदनादि तैलम', ['Cooling', 'Burning Sensation', 'Mental Stress'], 'External', 'Body Massage', 'मालिश करें'],
    ['Manjisthadi Tailam', 'मंजिष्ठादि तैलम', ['Complexion', 'Pigmentation', 'Uneven Tone'], 'External', 'Face Oil', 'चेहरे पर लगाएं'],
    ['Saffron Gel', 'केसर जेल', ['Glow', 'Fairness', 'Hydration'], 'External', 'Face Apply', 'चेहरे पर लगाएं'],
    ['Aloe Vera Gel', 'एलोवेरा जेल', ['Acne', 'Hydration', 'Burns'], 'External', 'Face/Body', 'लगाएं'],
    ['Rose Face Pack', 'गुलाब फेस पैक', ['Toning', 'Pores', 'Glow'], 'External', 'Face Pack', 'चेहरे पर लगाएं'],
    ['Neem Face Pack', 'नीम फेस पैक', ['Acne', 'Pimples', 'Oily Skin'], 'External', 'Face Pack', 'चेहरे पर लगाएं'],
    ['Multani Mitti', 'मुल्तानी मिट्टी', ['Oil Control', 'Cleaning', 'Cooling'], 'External', 'Face Pack', 'लेप लगाएं'],
    ['Rakta Chandan Powder', 'रक्त चंदन', ['Acne Scars', 'Cooling', 'Glow'], 'External', 'Face Pack', 'लेप लगाएं'],
    ['Sandalwood Powder', 'चंदन पाउडर', ['Cooling', 'Fairness', 'Soothing'], 'External', 'Face Pack', 'लेप लगाएं'],
    ['Orange Peel Powder', 'संतरा छिलका पाउडर', ['Vitamin C', 'Tan Removal', 'Brightening'], 'External', 'Scrub', 'स्क्रब करें'],
    ['Papaya Gel', 'पपीता जेल', ['Pigmentation', 'Softness', 'Exfoliation'], 'External', 'Massage', 'चेहरे की मालिश'],
    ['Cucumber Toner', 'खीरा टोनर', ['Pores', 'Freshness', 'Hydration'], 'Spray', 'Face Spray', 'चेहरे पर छिड़कें'],
    ['Almond Oil (Sweet)', 'बादाम तेल', ['Dark Circles', 'Dry Skin', 'Glow'], 'External', 'Under Eye', 'आंखों के नीचे लगाएं'],
    ['Castor Oil (Eyelashes)', 'अरंडी तेल', ['Eyelash Growth', 'Eyebrows'], 'External', 'Apply gently', 'पलकों पर लगाएं'],
    ['Bhringraj Powder', 'भृंगराज पाउडर', ['Hair Growth', 'Dark Hair'], 'External', 'Hair Pack', 'बालों में लगाएं'],
    ['Amla Powder', 'आंवला पाउडर', ['Hair Shine', 'Volume', 'Conditioning'], 'External', 'Hair Pack', 'बालों में लगाएं'],
    ['Shikakai Powder', 'शिकाकाई पाउडर', ['Cleansing', 'Softness', 'Dandruff'], 'External', 'Shampoo', 'बाल धोने के लिए'],
    ['Reetha Powder', 'रीठा पाउडर', ['Natural Cleanser', 'Gloss'], 'External', 'Shampoo', 'बाल धोने के लिए'],
    ['Hibiscus Powder', 'गुडहल पाउडर', ['Hair Growth', 'Conditioning', 'Redness'], 'External', 'Hair Pack', 'बालों में लगाएं'],
    ['Fenugreek Paste', 'मेथी पेस्ट', ['Dandruff', 'Cooling', 'Softness'], 'External', 'Hair Mask', 'बालों में लगाएं'],
    ['Curry Leaf Oil', 'कढ़ी पत्ता तेल', ['Premature Greying', 'Growth'], 'External', 'Hair Oil', 'सिर में लगाएं'],
    ['Onion Seed Oil', 'कलौंजी तेल', ['Hair Regrowth', 'Bald Spots'], 'External', 'Spot Apply', 'गंजेपन पर लगाएं'],
    ['Tea Tree Oil', 'टी ट्री ऑइल', ['Acne', 'Dandruff', 'Fungal'], 'External', 'Diluted Apply', 'तेल में मिलाकर लगाएं'],
    ['Lemon Honey Pack', 'नींबू शहद पैक', ['Detox', 'Tan', 'Glow'], 'External', 'Face Pack', 'चेहरे पर लगाएं'],
    ['Besan Haldi Pack', 'बेसन हल्दी', ['Traditional Glow', 'Hair Removal'], 'External', 'Ubtan', 'उबटन'],
    ['Coconut Milk Mask', 'नारियल दूध', ['Deep Conditioning', 'Dryness'], 'External', 'Hair Mask', 'बालों में लगाएं'],
    ['Yogurt Mask', 'दही पैक', ['Probiotic', 'Brightness', 'Moisture'], 'External', 'Face/Hair', 'लगाएं'],
    ['Tomato Juice', 'टमाटर रस', ['Open Pores', 'Oiliness', 'Tan'], 'External', 'Rub', 'चेहरे पर रगड़ें'],
    ['Potato Juice', 'आलू रस', ['Dark Circles', 'Pigmentation'], 'External', 'Apply', 'आंखों के नीचे लगाएं'],
    ['Rice Water', 'चावल का पानी', ['Skin Toner', 'Hair Growth'], 'Wash', 'Rinse', 'बाल/चेहरा धोएं'],
    ['Green Tea Toner', 'ग्रीन टी टोनर', ['Antioxidant', 'Acne'], 'Spray', 'Face', 'छिड़कें'],
    ['Mint Paste', 'पुदीना लेप', ['Acne', 'Cooling', 'Itch'], 'External', 'Apply', 'मुहांसों पर लगाएं'],
    ['Tulsi Paste', 'तुलसी लेप', ['Infection', 'Acne', 'Purify'], 'External', 'Apply', 'लगाएं'],
    ['Varnya Gana Kashayam', 'वर्ण्य गण कषायम', ['Skin Glow', 'Blood Purify'], '15ml', 'Twice daily', 'खाली पेट'],
    ['Manjisthadi Kwath', 'मंजिष्ठादि क्वाथ', ['Skin Detox', 'Acne'], '15ml', 'Twice daily', 'खाली पेट'],
    ['Khadirarishta', 'खदिरारिष्ट', ['Skin Allergies', 'Detox'], '20ml', 'After Food', 'पानी के साथ'],
    ['Sarivadyasava', 'सारिवाद्यासव', ['Cooling', 'Blood Purify'], '20ml', 'After Food', 'पानी के साथ'],
    ['Somraji Tailam', 'सोमराजी तैलम', ['White Spots', 'Psoriasis'], 'External', 'Apply', 'सफेद दाग पर'],
    ['Tuvaraka Tailam', 'तुवरक तैलम', ['Chronic Skin', 'Eczema'], 'External', 'Apply', 'लगाएं'],
    ['Psoria Oil', 'सोरिया तेल', ['Psoriasis', 'Scales'], 'External', 'Apply', 'लगाएं'],
    ['Winsoria Oil', 'विन्सोरिया तेल', ['Psoriasis', 'Itch'], 'External', 'Apply', 'लगाएं'],
    ['Cutis Oil', 'क्यूटिस तेल', ['Fungal', 'Itch', 'Eczema'], 'External', 'Apply', 'लगाएं']
];

export const home = [
    ['Ajwain Water', 'अजवायन पानी', ['Gas', 'Bloating', 'Colic'], '1 cup', 'Warm', 'घूंट घूंट पिएं'],
    ['Jeera Water', 'जीरा पानी', ['Digestion', 'Weight Loss', 'Cooling'], '1 cup', 'Morning', 'खाली पेट'],
    ['Saunf Water', 'सौंफ पानी', ['Acidity', 'Fresh Breath', 'Digestion'], '1 cup', 'After Meal', 'भोजन के बाद'],
    ['Dhaniya Water', 'धनिया पानी', ['Thyroid', 'Burning', 'Heat'], '1 cup', 'Morning', 'रात भर भीगा हुआ'],
    ['Methi Water', 'मेथी पानी', ['Diabetes', 'Joints', 'Weight'], '1 cup', 'Morning', 'भीगा हुआ बीज चबाएं'],
    ['Turmeric Milk', 'हल्दी दूध', ['Immunity', 'Pain', 'Sleep'], '1 cup', 'Night', 'सोते समय'],
    ['Ginger Tea', 'अदरक चाय', ['Cold', 'Flu', 'Digestion'], '1 cup', 'Anytime', 'घूंट घूंट पिएं'],
    ['Garlic Bud', 'लहसुन कली', ['Cholesterol', 'Heart', 'Gas'], '1 clove', 'Morning', 'खाली पेट निगलें'],
    ['Clove (Laung)', 'लौंग', ['Toothache', 'Cough', 'Bad Breath'], '1 piece', 'Chew', 'मुंह में रखें'],
    ['Cardamom (Elaichi)', 'इलायची', ['Nausea', 'Bad Breath', 'Acidity'], '1 piece', 'Chew', 'चबाएं'],
    ['Black Pepper & Honey', 'काली मिर्च शहद', ['Cough', 'Throat', 'Immunity'], '1 tsp', 'Lick', 'चाटें'],
    ['Tulsi Leaf', 'तुलसी पत्ता', ['Immunity', 'Cold', 'Fever'], '5 leaves', 'Morning', 'निगलें (चबाएं नहीं)'],
    ['Neem Leaf', 'नीम पत्ता', ['Detox', 'Skin', 'Diabetes'], '3 leaves', 'Morning', 'चबाएं'],
    ['Curry Leaf', 'कढ़ी पत्ता', ['Hair', 'Iron', 'Digestion'], '5 leaves', 'Morning', 'चबाएं'],
    ['Betel Leaf (Paan)', 'पान पत्ता', ['Digestion', 'Cough', 'Voice'], '1 leaf', 'After Meal', 'चबाएं'],
    ['Nutmeg (Jaiphal)', 'जायफल', ['Sleep', 'Diarrhea', 'Colic'], 'Pinch', 'Night Milk', 'दूध में घिसकर'],
    ['Saffron (Kesar)', 'केसर', ['Mood', 'Skin', 'Pregnancy'], '3 strands', 'Milk', 'दूध में'],
    ['Cinnamon Powder', 'दालचीनी', ['Sugar Control', 'Weight', 'PCOS'], 'Pinch', 'Tea/Water', 'चाय में'],
    ['Hing (Asafoetida)', 'हींग', ['Gas', 'Bloating', 'Pain'], 'Pinch', 'Warm Water/Navel', 'पानी में/नाभि पर'],
    ['Lemon Water', 'नींबू पानी', ['Detox', 'Vitamin C', 'Digestion'], '1 glass', 'Morning', 'गुनगुना'],
    ['Salt Water Gargle', 'नमक पानी', ['Sore Throat', 'Mouth Ulcer'], 'Gargle', 'As needed', 'कुल्ला करें'],
    ['Steam Inhalation', 'भाप', ['Cold', 'Sinus', 'Congestion'], 'Inhale', 'As needed', 'भाप लें'],
    ['Oil Pulling', 'तेल कुल्ला', ['Oral Detox', 'Teeth', 'Jaw'], '1 tbsp', 'Morning', 'मुंह में घुमाएं'],
    ['Nasya (Ghee)', 'देसी घी नस्य', ['Brain', 'Sinus', 'Sleep'], '2 drops', 'Nose', 'नाक में डालें'],
    ['Navel Oiling', 'नाभि पूरण', ['Dryness', 'Digestion', 'Skin'], '2 drops', 'Navel', 'नाभि में डालें'],
    ['Foot Massage', 'पादभ्यंग', ['Sleep', 'Eyes', 'Relax'], 'Oil', 'Solse', 'तलवों की मालिश'],
    ['Head Massage', 'शिरोभ्यंग', ['Stress', 'Hair', 'Sleep'], 'Oil', 'Head', 'सिर की मालिश'],
    ['Body Scrub (Ubtan)', 'उबटन', ['Skin', 'Circulation'], 'Paste', 'Bath', 'रगड़ें'],
    ['Sun Bathing', 'धूप स्नान', ['Vitamin D', 'Bones', 'Mood'], '20 mins', 'Morning', 'धूप में बैठें'],
    ['Copper Water', 'तांबा पानी', ['Detox', 'Digestion'], '1 glass', 'Morning', 'रात भर रखा हुआ'],
    ['Clay Pot Water', 'मिट्टी घड़ा पानी', ['Alkaline', 'Cooling'], 'Drink', 'All Day', 'दिन भर पिएं'],
    ['Silver Water', 'चांदी पानी', ['Cooling', 'Immunity'], 'Drink', 'All Day', 'चांदी का सिक्का डालकर'],
    ['Gold Water', 'स्वर्ण जल', ['Immunity', 'Brain', 'Strength'], 'Boiled', 'Tonic', 'सोना उबालकर'],
    ['Rice Gruel (Kanji)', 'पेज (मांड)', ['Weakness', 'Digestion', 'Fever'], 'Bowl', 'Diet', 'पिएं'],
    ['Mung Dal Soup', 'मूंग दाल सूप', ['Recovery', 'Protein', 'Light'], 'Bowl', 'Dinner', 'पिएं'],
    ['Buttermilk (Chaas)', 'छाछ', ['Digestion', 'Cooling', 'IBS'], '1 glass', 'Lunch', 'जीरा डालकर'],
    ['Ghee with Rice', 'घी चावल', ['Brain', 'Digestion', 'Strength'], '1 tsp', 'Lunch', 'मिलाकर खाएं'],
    ['Roasted Garlic', 'भुना लहसुन', ['Vaata', 'Pain', 'Heart'], '2 cloves', 'Dinner', 'खाएं'],
    ['Soaked Almonds', 'भीगे बादाम', ['Brain', 'Strength'], '5 nuts', 'Morning', 'छीलकर खाएं'],
    ['Soaked Raisins', 'मुनक्का', ['Constipation', 'Iron'], '10 pcs', 'Morning', 'भीगा हुआ'],
    ['Soaked Figs (Anjeer)', 'अंजीर', ['Constipation', 'Calcium'], '2 pcs', 'Morning', 'भीगा हुआ'],
    ['Dates (Khajoor)', 'खजूर', ['Energy', 'Iron'], '2 pcs', 'Snack', 'खाएं'],
    ['Jaggery & Ghee', 'गुड़ घी', ['Destory', 'Energy', 'Immunity'], '1 tsp', 'Creating', 'मिलाकर खाएं'],
    ['Rock Sugar (Mishri)', 'मिश्री', ['Cough', 'Burning', 'Cooling'], 'Lump', 'Suck', 'चूसें'],
    ['Fennel Seeds (After meal)', 'सौंफ', ['Digestion', 'Mouth Fresh'], '1 tsp', 'After Meal', 'चबाएं'],
    ['Betel Nut (Supari)', 'सुपारी', ['Astringent', 'Digestion'], 'Small', 'Occasional', 'चबाएं'],
    ['Hot Water', 'गर्म पानी', ['Metabolism', 'Kapha', 'Fat'], 'Sip', 'All Day', 'पिएं'],
    ['Cold Bath', 'ठंडे पानी से स्नान', ['Pitta', 'Alertness'], 'Bath', 'Morning', 'नहाएं'],
    ['Warm Bath', 'गर्म पानी से स्नान', ['Vata', 'Pain', 'Relax'], 'Bath', 'Evening', 'नहाएं'],
    ['Meditation', 'ध्यान', ['Mind', 'Stress', 'Soul'], '10 mins', 'Morning', 'आंखें बंद करें'],
    ['Pranayama', 'प्राणायाम', ['Lungs', 'Energy', 'Mind'], '10 mins', 'Morning', 'सांस का व्यायाम']
];

export const singleHerbs = [
    ['Ashwagandha Root', 'अश्वगंधा जड़', ['Stress', 'Strength', 'Sleep'], '1 tsp', 'Night Milk', 'दूध में उबालकर'],
    ['Shatavari Root', 'शतावरी जड़', ['Hormones', 'Cooling', 'Strength'], '1 tsp', 'Morning Milk', 'दूध के साथ'],
    ['Brahmi Leaf', 'ब्राह्मी', ['Memory', 'Cooling', 'Focus'], '1 tsp', 'Morning Water', 'पानी के साथ'],
    ['Shankhpushpi', 'शंखपुष्पी', ['Brain', 'Sleep', 'Anxiety'], '1 tsp', 'Night Milk', 'दूध के साथ'],
    ['Jatamansi', 'जटामांसे', ['Sleep', 'Relaxation', 'BP'], '1/2 tsp', 'Night', 'शहद के साथ'],
    ['Guduchi (Giloy)', 'गुडूची', ['Immunity', 'Fever', 'Detox'], '1 tsp', 'Morning', 'पानी के साथ'],
    ['Amla Fruit', 'आंवला', ['Vitamin C', 'Hair', 'Acidity'], '1 tsp', 'Morning', 'पानी के साथ'],
    ['Haritaki (Harad)', 'हरीतकी', ['Constipation', 'Detox', 'Eyes'], '1 tsp', 'Night', 'गुनगुने पानी के साथ'],
    ['Bibhitaki (Baheda)', 'विभीतक', ['Cough', 'Throat', 'Hair'], '1 tsp', 'Morning', 'शहद के साथ'],
    ['Gokshura Fruit', 'गोक्षुर', ['Kidney', 'Muscle', 'Urine'], '1 tsp', 'Morning', 'पानी के साथ'],
    ['Punarnava Root', 'पुनर्नवा', ['Kidney', 'Swelling', 'Liver'], '1 tsp', 'Morning', 'पानी के साथ'],
    ['Manjistha Root', 'मंजिष्ठा', ['Blood', 'Skin', 'Detox'], '1 tsp', 'Morning', 'पानी के साथ'],
    ['Neem Leaf', 'नीम', ['Skin', 'Diabetes', 'Detox'], '1/2 tsp', 'Morning', 'पानी के साथ'],
    ['Tulsi Leaf', 'तुलसी', ['Cold', 'Flu', 'Immunity'], '1 tsp', 'Morning', 'शहद के साथ'],
    ['Bhringraj', 'भृंगराज', ['Hair', 'Liver', 'Teeth'], '1 tsp', 'Morning', 'शहद के साथ'],
    ['Arjuna Bark', 'अर्जुन छाल', ['Heart', 'BP', 'Cholesterol'], '1 tsp', 'Morning Milk', 'दूध में उबालकर'],
    ['Pippali (Long Pepper)', 'पिप्पली', ['Lungs', 'Cold', 'Digestion'], 'pinch', 'Honey', 'शहद के साथ'],
    ['Maricha (Black Pepper)', 'काली मिर्च', ['Absorption', 'Cough', 'Fat'], 'pinch', 'Honey', 'शहद के साथ'],
    ['Shunthi (Dry Ginger)', 'सोंठ', ['Digestion', 'Pain', 'Gas'], '1/2 tsp', 'Warm Water', 'गर्म पानी'],
    ['Elaichi (Cardamom)', 'इलायची', ['Nausea', 'Acidity', 'Flavor'], '1 pod', 'Chew', 'चबाएं'],
    ['Twak (Cinnamon)', 'दालचीनी', ['Sugar', 'Fat', 'PCOS'], 'pinch', 'Tea', 'चाय में'],
    ['Nagkesar', 'नागकेसर', ['Bleeding', 'Piles', 'Heat'], '1/2 tsp', 'Butter/Water', 'मक्खन के साथ'],
    ['Vidanga', 'विडंग', ['Worms', 'Bacteria', 'Fat'], '1/2 tsp', 'Night', 'पानी के साथ'],
    ['Musta (Nutgrass)', 'मुस्त', ['Digestion', 'Fever', 'IBS'], '1 tsp', 'Morning', 'पानी के साथ'],
    ['Chitrak Root', 'चित्रक', ['Metabolism', 'Piles', 'Fat'], 'pinch', 'Honey', 'शहद के साथ (कम मात्रा)'],
    ['Kutki', 'कुटकी', ['Liver', 'Fever', 'Detox'], 'pinch', 'Honey', 'शहद के साथ'],
    ['Chirata', 'चिरायता', ['Blood Purify', 'Skin', 'Fever'], 'decoction', 'Night', 'काढ़ा पिएं'],
    ['Kalmegh', 'कालमेघ', ['Lever', 'Immunity', 'Viral'], '1/2 tsp', 'Water', 'पानी के साथ'],
    ['Ativisha', 'अतिविषा', ['Diarrhea', 'Fever', 'Kids'], 'pinch', 'Honey', 'शहद के साथ'],
    ['Vacha (Sweet Flag)', 'वचा', ['Speech', 'Memory', 'Voice'], 'pinch', 'Honey', 'शहद के साथ'],
    ['Jyotishmati', 'ज्योतिष्मती', ['Memory', 'Brain', 'Focus'], '2 drops', 'Milk', 'दूध में'],
    ['Kapikacchu', 'कपिकच्छु', ['Nerves', 'Strength', 'Tremors'], '1 tsp', 'Milk', 'दूध के साथ'],
    ['Safed Musli', 'सफेद मूसली', ['Strength', 'Weight', 'Energy'], '1 tsp', 'Milk', 'दूध के साथ'],
    ['Vidarikand', 'विदारीकंद', ['Weight', 'Strength', 'Cooling'], '1 tsp', 'Milk', 'दूध के साथ'],
    ['Bala Root', 'बला', ['Strength', 'Nerves', 'Pain'], '1 tsp', 'Milk', 'दूध के साथ'],
    ['Shalparni', 'शालपर्णी', ['Fever', 'Heart', 'Vata'], '1 tsp', 'Water', 'पानी के साथ'],
    ['Prishniparni', 'पृश्निपर्णी', ['Fracture', 'Cough', 'Diarrhea'], '1 tsp', 'Water', 'पानी के साथ'],
    ['Kantakari', 'कंटकारी', ['Cough', 'Asthma', 'Throat'], '1 tsp', 'Honey', 'शहद के साथ'],
    ['Brihati', 'वृहती', ['Cough', 'Throat', 'Heart'], '1 tsp', 'Honey', 'शहद के साथ'],
    ['Bilva Fruit', 'बिल्व', ['Diarrhea', 'IBS', 'Gut'], '1 tsp', 'Curd', 'दही के साथ'],
    ['Agnimantha', 'अग्निमंथ', ['Weight', 'Swelling', 'Pain'], '1 tsp', 'Water', 'पानी के साथ'],
    ['Shyonak', 'श्योनाक', ['Diarrhea', 'Pain', 'Cough'], '1 tsp', 'Water', 'पानी के साथ'],
    ['Patala', 'पाठा', ['Acid', 'Vomit', 'Wounds'], '1 tsp', 'Water', 'पानी के साथ'],
    ['Gambhari', 'गंभारी', ['Fever', 'Thirst', 'Strength'], '1 tsp', 'Water', 'पानी के साथ'],
    ['Lodhra', 'लोध्र', ['Bleeding', 'Women', 'Skin'], '1 tsp', 'Rice Water', 'चावल के पानी के साथ'],
    ['Ashoka Bark', 'अशोक छाल', ['Uterus', 'Bleeding', 'Pain'], 'decoction', 'Morning', 'काढ़ा बनाकर'],
    ['Sarpagandha', 'सर्पगंधा', ['BP', 'Sleep', 'Mind'], 'tablet', 'Doctor', 'डॉक्टर की सलाह से'],
    ['Guggulu Purified', 'शुद्ध गुग्गुलु', ['Pain', 'Fat', 'Arthritis'], 'tablet', 'Warm Water', 'गर्म पानी'],
    ['Shilajit Purified', 'शुद्ध शिलाजीत', ['Energy', 'Sugar', 'Aging'], 'drop/cap', 'Milk', 'दूध के साथ'],
    ['Yashtimadhu (Mulethi)', 'यष्टिमधु', ['Acid', 'Throat', 'Cough'], '1/2 tsp', 'Honey', 'शहद के साथ'],
    ['Sariva (Anantmool)', 'सारिवा', ['Cooling', 'Skin', 'Blood'], '1 tsp', 'Water', 'पानी के साथ'],
    ['Ushira (Khus)', 'उशीर', ['Cooling', 'Thirst', 'Burning'], 'water', 'All Day', 'पानी में डालकर'],
    ['Chandan (White)', 'सफेद चंदन', ['Cooling', 'Mind', 'Acid'], 'paste', 'External', 'माथे पर'],
    ['Raktachandan', 'रक्त चंदन', ['Skin', 'Cooling', 'Pimples'], 'paste', 'External', 'चेहरे पर'],
    ['Khadira', 'खदिर', ['Skin', 'Blood', 'Teeth'], 'decoction', 'Morning', 'काढ़ा'],
    ['Babool', 'बबूल', ['Teeth', 'Bone', 'Healing'], 'powder', 'Gums', 'मंजन'],
    ['Apamarga', 'अपामार्ग', ['Hunger', 'Stone', 'Cleanse'], 'seeds', 'Kheer', 'खीर बनाकर'],
    ['Varuna', 'वरुण', ['Stone', 'Prostate', 'Urine'], 'decoction', 'Morning', 'काढ़ा'],
    ['Pashanbhed', 'पाषाणभेद', ['Stone', 'Urine', 'Pain'], 'powder', 'Water', 'पानी के साथ'],
    ['Moringa', 'सहजन', ['Nutrition', 'Eyes', 'BP'], 'leaves', 'Food', 'सब्जी/सूप']
];

export const bhasma = [
    ['Swarna Bhasma', 'स्वर्ण भस्म', ['Immunity', 'Brain', 'Aging'], '15mg', 'Honey/Ghee', 'शहद और घी (विषम मात्रा)'],
    ['Rajat Bhasma', 'रजत भस्म', ['Nerves', 'Cooling', 'Mind'], '125mg', 'Honey', 'शहद के साथ'],
    ['Tamra Bhasma', 'ताम्र भस्म', ['Liver', 'Spleen', 'Tumor'], 'Consult Dr', 'Doctor', 'डॉक्टर की सलाह से'],
    ['Loha Bhasma', 'लौह भस्म', ['Anemia', 'Strength', 'Liver'], '125mg', 'Honey', 'शहद के साथ'],
    ['Abhrak Bhasma (1000)', 'अभ्रक भस्म (सहस्त्र)', ['Chronic', 'Respiratory', 'Vitality'], '125mg', 'Honey', 'शहद के साथ'],
    ['Vanga Bhasma', 'वंग भस्म', ['Urinary', 'Diabetes', 'Strength'], '125mg', 'Honey', 'शहद के साथ'],
    ['Yashad Bhasma', 'यशद भस्म', ['Eyes', 'Diabetes', 'Healing'], '125mg', 'Honey', 'शहद के साथ'],
    ['Naga Bhasma', 'नाग भस्म', ['Diabetes', 'Nerves', 'Incontinence'], 'Consult Dr', 'Doctor', 'डॉक्टर की सलाह से'],
    ['Praval Bhasma', 'प्रवाल भस्म', ['Calcium', 'Acid', 'Heat'], '250mg', 'Honey', 'शहद के साथ'],
    ['Mukta Bhasma', 'मुक्ता भस्म', ['Cooling', 'Mind', 'Heart'], '125mg', 'Honey', 'शहद के साथ'],
    ['Shankha Bhasma', 'शंख भस्म', ['Acid', 'Pain', 'Digestion'], '250mg', 'Lemon Water', 'नींबू पानी'],
    ['Kapardika Bhasma', 'कपर्दिका भस्म', ['Pain', 'Digestion', 'Ear'], '250mg', 'Honey', 'शहद के साथ'],
    ['Godanti Bhasma', 'गोदंती भस्म', ['Fever', 'Headache', 'Calcium'], '500mg', 'Honey', 'शहद के साथ'],
    ['Sphatika Bhasma', 'स्फटिक भस्म', ['Bleeding', 'Throat', 'Skin'], '125mg', 'Honey', 'शहद के साथ'],
    ['Tankan Bhasma', 'टंकण भस्म', ['Cough', 'Dandruff', 'Periods'], '125mg', 'Honey', 'शहद के साथ'],
    ['Kasis Bhasma', 'कसीस भस्म', ['Anemia', 'Liver', 'Spleen'], '125mg', 'Honey', 'शहद के साथ'],
    ['Mandur Bhasma', 'मंडूर भस्म', ['Anemia', 'Liver', 'Jaundice'], '250mg', 'Honey', 'शहद के साथ'],
    ['Mayur Picha Bhasma', 'मयूर पिछ भस्म', ['Vomit', 'Hiccup', 'Asthma'], '125mg', 'Honey', 'शहद के साथ'],
    ['Jahar Mohra Pishti', 'जहर मोहरा', ['Heart', 'Kids', 'Strength'], '125mg', 'Honey', 'शहद के साथ'],
    ['Akik Pishti', 'अकीक पिष्टी', ['Heart', 'Brain', 'Cooling'], '125mg', 'Honey', 'शहद के साथ'],
    ['Sangeyashab Pishti', 'संगयशब पिष्टी', ['Heart', 'Weakness', 'Pitta'], '250mg', 'Honey', 'शहद के साथ'],
    ['Kaharwa Pishti', 'कहर्वा पिष्टी', ['Bleeding', 'Heart', 'Piles'], '250mg', 'Honey', 'शहद के साथ'],
    ['Manikya Pishti', 'माणिक्य पिष्टी', ['Heart', 'Energy', 'Drive'], 'Consult Dr', 'Honey', 'शहद के साथ'],
    ['Panna Pishti', 'पन्ना पिष्टी', ['Fever', 'Vomit', 'Poison'], 'Consult Dr', 'Honey', 'शहद के साथ'],
    ['Neelam Pishti', 'नीलम पिष्टी', ['Pain', 'Vata', 'Arthritis'], 'Consult Dr', 'Honey', 'शहद के साथ'],
    ['Heera Bhasma', 'हीरा भस्म', ['Cancer', 'Tumor', 'Vitality'], 'Consult Dr', 'Critical', 'विशेषज्ञ की सलाह'],
    ['Swarna Makshik', 'स्वर्ण माक्षिक', ['Diabetes', 'Eyes', 'Sleep'], '125mg', 'Honey', 'शहद के साथ'],
    ['Rasa Sindoor', 'रस सिंदूर', ['Immunity', 'Syphilis', 'Strength'], 'Consult Dr', 'Doctor', 'डॉक्टर की सलाह से'],
    ['Makaradhwaj', 'मकरध्वज', ['Vitality', 'Nerves', 'Power'], '125mg', 'Betel Leaf', 'पान के साथ'],
    ['Siddha Makaradhwaj', 'सिद्ध मकरध्वज', ['Action', 'Energy', 'Heart'], '125mg', 'Honey', 'शहद के साथ'],
    ['Sameer Pannag Ras', 'समीर पन्नग', ['Paralysis', 'Asthma', 'Joints'], '60mg', 'Honey', 'शहद के साथ'],
    ['Malla Sindoor', 'मल्ल सिंदूर', ['Vata', 'Pain', 'Asthma'], 'Consult Dr', 'Doctor', 'आपातकालीन'],
    ['Vat Vidhwansan', 'वात विध्वंसन', ['Severe Pain', 'Nerves'], '1 tab', 'Ginger', 'अदरक रस'],
    ['Maha Vat Vidhwansan', 'महा वात विध्वंसन', ['Paralysis', 'Epilepsy'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Ekangvir Ras', 'एकांगवीर रस', ['Paralysis', 'Sciatica', 'Bells Palsy'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Rasraj Ras', 'रसराज रस', ['Brain', 'Paralysis', 'Stroke'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Yogendra Ras', 'योगेंद्र रस', ['Diabetes', 'Nerves', 'Heart'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Vasant Kusumakar', 'वसंत कुसुमाकर', ['Diabetes', 'Vitality'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Brihat Vata Chintamani', 'वृहत् वात चिंतामणि', ['Heart', 'Brain', 'Nerves'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Trailokya Chintamani', 'त्रैलोक्य चिंतामणि', ['Heart', 'Fluids', 'Strength'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Swarna Malini Vasant', 'स्वर्ण मालिनी वसंत', ['Fever', 'Pregnancy', 'Kids'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Hemgarbha Potli', 'हेमगर्भ पोटली', ['Emergency', 'Heart', 'Coma'], 'Rub', 'Tongue', 'जीभ पर घिसें'],
    ['Hiranyagarbha Potli', 'हिरण्यगर्भ पोटली', ['Asthma', 'Emergency'], 'Rub', 'Tongue', 'जीभ पर घिसें'],
    ['Loknath Ras', 'लोकनाथ रस', ['Liver', 'Spleen', 'Digestion'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Arogyavardhini', 'आरोग्यवर्धिनी', ['Liver', 'Skin', 'Obesity'], '2 tabs', 'Water', 'पानी के साथ'],
    ['Sutshekhar', 'सूतशेखर', ['Acid', 'Vomit', 'Headache'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Kamdudha (Moti)', 'कामदुधा (मोती)', ['Heat', 'Bleeding', 'Anger'], '1 tab', 'Water', 'पानी के साथ'],
    ['Chandrakala', 'चंद्रकला', ['Heat', 'Diabetes', 'Bleeding'], '1 tab', 'Water', 'पानी के साथ'],
    ['Laghu Sut Shekhar', 'लघु सूतशेखर', ['Acid', 'Headache', 'Giddy'], '1 tab', 'Water', 'पानी के साथ'],
    ['Gandhak Rasayan', 'गंधक रसायन', ['Infection', 'Skin', 'Blood'], '2 tabs', 'Milk', 'दूध के साथ']
];

export const oils = [
    ['Mahanarayan Tailam', 'महानारायण तेल', ['Joint Pain', 'Stiffness', 'Strength'], 'External', 'Massage', 'मालिश करें'],
    ['Dhanwantharam Tailam', 'धन्वंतरम तेल', ['Post-Natal', 'Pain', 'Nerves'], 'External', 'Massage', 'मालिश करें'],
    ['Ksheerabala Tailam', 'क्षीरबला तेल', ['Nerves', 'Insomnia', 'Pain'], 'External', 'Massage', 'सिर/शरीर मालिश'],
    ['Sahacharadi Tailam', 'सहचरादि तेल', ['Sciatica', 'Leg Pain', 'Varicose'], 'External', 'Massage', 'पैरों की मालिश'],
    ['Karpuradi Tailam', 'कर्पूरादि तेल', ['Cramps', 'Pain', 'Chest Congestion'], 'External', 'Rub', 'लगाएं'],
    ['Murivenna', 'मुरिवेन्ना', ['Fracture', 'Wound', 'Sprain'], 'External', 'Apply', 'चोट पर लगाएं'],
    ['Pinda Tailam', 'पिंड तेल', ['Gout', 'Burning', 'Redness'], 'External', 'Gentle', 'हल्के हाथ से लगाएं'],
    ['Balashwagandhadi', 'बलाअश्वगंधादि', ['Strength', 'Muscle', 'Fever'], 'External', 'Massage', 'मालिश करें'],
    ['Himasagara Tailam', 'हिमसागर तेल', ['Brain', 'Cooling', 'Crazy'], 'External', 'Head', 'सिर पर लगाएं'],
    ['Vachadi Tailam', 'वचादि तेल', ['Swelling', 'Lymph', 'Nodes'], 'External', 'Apply', 'लगाएं'],
    ['Anu Tailam', 'अणु तैलम', ['Sinus', 'Nose', 'Headache'], '2 drops', 'Nose', 'नाक में डालें'],
    ['Shadbindu Tailam', 'षडबिंदु तैलम', ['Migraine', 'Hair', 'Sinus'], '2 drops', 'Nose', 'नाक में डालें'],
    ['Kuntalkanti Tailam', 'कुंतलकांति', ['Hair', 'Dandruff', 'Lice'], 'External', 'Hair', 'बालों में लगाएं'],
    ['Kayyanyadi Tailam', 'कय्यन्यादि', ['Greying', 'Eyes', 'Headache'], 'External', 'Head', 'सिर पर लगाएं'],
    ['Neelibhringadi', 'नीलीभृंगादि', ['Black Hair', 'Growth', 'Cooling'], 'External', 'Head', 'सिर पर लगाएं'],
    ['Chemparuthyadi', 'चेम्परुथ्यादि', ['Itching', 'Eczema', 'Skin'], 'External', 'Skin', 'लगाएं'],
    ['Nalpamaradi', 'नालपामरादि', ['Tan', 'Glow', 'Itch'], 'External', 'Body', 'नहाने से पहले'],
    ['Eladi Tailam', 'एलादि तेल', ['Infection', 'Acne', 'Detox'], 'External', 'Body', 'लगाएं'],
    ['Kumkumadi', 'कुमकुमादि', ['Face Glow', 'Spots', 'Acne'], 'External', 'Face', 'चेहरे पर लगाएं'],
    ['Jatyadi Tailam', 'जात्यादि तेल', ['Wound', 'Ulcer', 'Cut'], 'External', 'Wound', 'घाव पर'],
    ['Tuvaraka Tailam', 'तुवरक तेल', ['Severe Skin', 'Psoriasis'], 'External', 'Apply', 'लगाएं'],
    ['Somraji Tailam', 'सोमराजी तेल', ['Leucoderma', 'Itch'], 'External', 'Apply', 'सफेद दाग पर'],
    ['Karanj Tailam', 'करंज तेल', ['Infection', 'Worm', 'Skin'], 'External', 'Apply', 'लगाएं'],
    ['Neem Tailam', 'नीम तेल', ['Infection', 'Insect', 'Skin'], 'External', 'Apply', 'लगाएं'],
    ['Narikela (Coconut)', 'नारियल तेल', ['Burn', 'Hair', 'Skin'], 'External', 'Apply', 'लगाएं'],
    ['Badam Rogan', 'बादाम रोगन', ['Brain', 'Skin', 'Nose'], '5 drops', 'Milk/Nose', 'नाक या दूध में'],
    ['Jyotishmati Oil', 'ज्योतिष्मती तेल', ['Memory', 'Pain', 'Focus'], '2 drops', 'Milk', 'दूध में'],
    ['Maha Mash Tailam', 'महामाष तेल', ['Paralysis', 'Weakness', 'Vata'], 'External', 'Massage', 'मालिश करें'],
    ['Vishgarbha Tailam', 'विषगर्भ तेल', ['Deep Pain', 'Sciatica', 'Locked'], 'External', 'Massage', 'मालिश करें'],
    ['Prasarini Tailam', 'प्रसारिणी तेल', ['Frozen Shoulder', 'Stiffness'], 'External', 'Massage', 'मालिश करें'],
    ['Kottamchukkadi', 'कोट्टमचुक्कादि', ['Swelling', 'Pain', 'Rheumatoid'], 'External', 'Apply', 'लगाएं'],
    ['Gandha Tailam', 'गंध तेल', ['Bone fracture', 'Ligament'], '5 drops', 'Milk', 'दूध के साथ'],
    ['Kshara Tailam', 'क्षार तेल', ['Ear', 'Wax', 'Pain'], '2 drops', 'Ear', 'कान में डालें'],
    ['Bilva Tailam', 'बिल्व तेल', ['Ear', 'Hearing', 'Pain'], '2 drops', 'Ear', 'कान में डालें'],
    ['Irimedadi Tailam', 'इरिमेदादि', ['Teeth', 'Gum', 'Mouth'], 'Gargle', 'Mouth', 'कुल्ला करें'],
    ['Arimedadi Tailam', 'अरिमेदादि', ['Teeth', 'Decay', 'Pain'], 'Gargle', 'Mouth', 'कुल्ला करें'],
    ['Panchaguna Tailam', 'पंचगुण तेल', ['Pain', 'Sprain', 'Swelling'], 'External', 'Apply', 'लगाएं'],
    ['Mahich Tailam', 'महिष तेल', ['Wait', 'Pain'], 'External', 'Apply', 'लगाएं'],
    ['Laghu Vishgarbha', 'लघु विषगर्भ', ['Pain', 'Stiffness'], 'External', 'Apply', 'लगाएं'],
    ['Brihat Saidhavadi', 'सैंधवादि', ['Joints', 'Vata'], 'External', 'Massage', 'मालिश']
];

export const ghrita = [
    ['Brahmi Ghrita', 'ब्राह्मी घृत', ['Memory', 'Brain', 'Stress'], '1 tsp', 'Morning', 'खाली पेट'],
    ['Kalyanaka Ghrita', 'कल्याणक घृत', ['Epilepsy', 'Mental', 'Infertility'], '1 tsp', 'Morning', 'खाली पेट'],
    ['Mahatiktaka Ghrita', 'महातिक्तक', ['Skin', 'Blood', 'Pitta'], '1 tsp', 'Morning', 'खाली पेट'],
    ['Panchatikta Ghrita', 'पंचतिक्त', ['Skin', 'Bone', 'Vata'], '1 tsp', 'Morning', 'खाली पेट'],
    ['Guggulutiktaka', 'गुग्गुलुतिक्तक', ['Joints', 'Skin', 'Deep'], '1 tsp', 'Morning', 'खाली पेट'],
    ['Indukanta Ghrita', 'इन्दुकान्त', ['Immunity', 'Gas', 'Weakness'], '1 tsp', 'Morning', 'खाली पेट'],
    ['Dadimadi Ghrita', 'दाडिमादि', ['Anemia', 'Heart', 'Delivery'], '1 tsp', 'Food', 'भोजन के साथ'],
    ['Phala Ghrita', 'फल घृत', ['Fertility', 'Uterus', 'Baby'], '1 tsp', 'Morning', 'खाली पेट'],
    ['Shatavaryadi', 'शतावर्यादि', ['Cooling', 'Women', 'Acid'], '1 tsp', 'Morning', 'खाली पेट'],
    ['Sukumara Ghrita', 'सुकुमार', ['Hernia', 'Constipation', 'Women'], '1 tsp', 'Morning', 'खाली पेट'],
    ['Amritaprasha', 'अमृतप्राश', ['Strength', 'Cough', 'Weight'], '1 tsp', 'Milk', 'दूध के साथ'],
    ['Ashwagandha Ghrita', 'अश्वगंधा घृत', ['Strength', 'Sex', 'Nerves'], '1 tsp', 'Milk', 'दूध के साथ'],
    ['Vidaryadi Ghrita', 'विदार्यादि', ['Weight', 'Vata', 'Dryness'], '1 tsp', 'Food', 'भोजन के साथ'],
    ['Dhanwantharam', 'धन्वंतरम', ['Diabetes', 'Toxic', 'Weakness'], '1 tsp', 'Morning', 'खाली पेट'],
    ['Triphala Ghrita', 'त्रिफला घृत', ['Eyes', 'Hair', 'Digestion'], '1 tsp', 'Night', 'दूध के साथ'],
    ['Maha Triphala', 'महा त्रिफला', ['Cataract', 'Vision', 'Eyes'], '1 tsp', 'Night', 'दूध के साथ'],
    ['Jatyadi Ghrita', 'जात्यादि घृत', ['Wound', 'Burn', 'Ulcer'], 'External', 'Wound', 'घाव पर'],
    ['Shatadhauta Ghrita', 'शतधौत घृत', ['Burn', 'Skin', 'Scar'], 'External', 'Skin', 'लगाएं'],
    ['Panchagavya', 'पंचगव्य', ['Epilepsy', 'Liver', 'Mind'], '1 tsp', 'Morning', 'खाली पेट'],
    ['Saraswata Ghrita', 'सारस्वत', ['Speech', 'Memory', 'Mind'], '1 tsp', 'Morning', 'खाली पेट'],
    ['Arjuna Ghrita', 'अर्जुन घृत', ['Heart', 'BP', 'Clot'], '1 tsp', 'Morning', 'खाली पेट'],
    ['Lasunadi Ghrita', 'लसुनादि', ['Vata', 'Pain', 'Cholesterol'], '1 tsp', 'Food', 'भोजन के साथ'],
    ['Hingvadi Ghrita', 'हिंग्वादि', ['Gas', 'Pain', 'Gut'], '1 tsp', 'Food', 'भोजन के साथ'],
    ['Changeri Ghrita', 'चांगेरी', ['Piles', 'Digestion', 'Prolapse'], '1 tsp', 'Food', 'भोजन के साथ']
];

export const asava = [
    ['Abhayarishta', 'अभयारिष्ट', ['Piles', 'Constipation', 'Gut'], '20ml', 'After Food', 'पानी के साथ'],
    ['Amritarishta', 'अमृतारिष्ट', ['Fever', 'Immunity', 'Weak'], '20ml', 'After Food', 'पानी के साथ'],
    ['Arjunarishta', 'अर्जुनारिष्ट', ['Heart', 'BP', 'Strength'], '20ml', 'After Food', 'पानी के साथ'],
    ['Ashokarishta', 'अशोकारिष्ट', ['Periods', 'Pain', 'Women'], '20ml', 'After Food', 'पानी के साथ'],
    ['Ashwagandharishta', 'अश्वगंधारिष्ट', ['Mind', 'Stress', 'Epilepsy'], '20ml', 'After Food', 'पानी के साथ'],
    ['Balarishta', 'बलारिष्ट', ['Nerves', 'Strength', 'Vata'], '20ml', 'After Food', 'पानी के साथ'],
    ['Chandanasava', 'चंदनासव', ['Sperm', 'Cooling', 'Burning'], '20ml', 'After Food', 'पानी के साथ'],
    ['Dashmoolarishta', 'दशमूलारिष्ट', ['Post-Natal', 'Pain', 'Energy'], '20ml', 'After Food', 'पानी के साथ'],
    ['Draksharishta', 'द्राक्षारिष्ट', ['Constipation', 'Strength', 'Cold'], '20ml', 'After Food', 'पानी के साथ'],
    ['Jeerakarishta', 'जीरकाद्यारिष्ट', ['Post-Natal', 'Milk', 'Gut'], '20ml', 'After Food', 'पानी के साथ'],
    ['Kanakasava', 'कनकासव', ['Asthma', 'Cough', 'Breath'], '15ml', 'After Food', 'पानी के साथ'],
    ['Khadirarishta', 'खदिरारिष्ट', ['Skin', 'Acne', 'Detox'], '20ml', 'After Food', 'पानी के साथ'],
    ['Kumaryasava', 'कुमार्यासव', ['Liver', 'Periods', 'Digest'], '20ml', 'After Food', 'पानी के साथ'],
    ['Kutajarishta', 'कुटजारिष्ट', ['Diarrhea', 'IBS', 'Dysentery'], '20ml', 'After Food', 'पानी के साथ'],
    ['Lohasava', 'लोहासव', ['Anemia', 'Weight', 'Spleen'], '20ml', 'After Food', 'पानी के साथ'],
    ['Mustakarishta', 'मुस्तकारिष्ट', ['Diarrhea', 'Indigestion', 'IBS'], '20ml', 'After Food', 'पानी के साथ'],
    ['Parthadyarishta', 'पार्थाद्यारिष्ट', ['Heart', 'Lung', 'Strength'], '20ml', 'After Food', 'पानी के साथ'],
    ['Patrangasava', 'पत्रांगासव', ['Bleeding', 'Periods', 'Cool'], '20ml', 'After Food', 'पानी के साथ'],
    ['Pippalyasava', 'पिप्पल्यासव', ['IBS', 'Cough', 'Anemia'], '20ml', 'After Food', 'पानी के साथ'],
    ['Punarnavasava', 'पुनर्नवासव', ['Liver', 'Kidney', 'Swelling'], '20ml', 'After Food', 'पानी के साथ'],
    ['Rohitakarishta', 'रोहितकारिष्ट', ['Spleen', 'Liver', 'Blood'], '20ml', 'After Food', 'पानी के साथ'],
    ['Saraswatarishta', 'सारस्वतारिष्ट', ['Memory', 'Mind', 'Stutter'], '20ml', 'After Food', 'पानी के साथ'],
    ['Sarivadyasava', 'सारिवाद्यासव', ['Diabetes', 'Skin', 'Cooling'], '20ml', 'After Food', 'पानी के साथ'],
    ['Usheerasava', 'उशीरासव', ['Bleeding', 'Heat', 'Anemia'], '20ml', 'After Food', 'पानी के साथ'],
    ['Vasarishta', 'वासारिष्ट', ['Cough', 'Asthma', 'Blood'], '20ml', 'After Food', 'पानी के साथ'],
    ['Drakshasava', 'द्राक्षासव', ['Energy', 'Piles', 'Gut'], '20ml', 'After Food', 'पानी के साथ'],
    ['Vidaryadi Asava', 'विदार्यादि', ['Weight', 'Vata', 'Thyroid'], '20ml', 'After Food', 'पानी के साथ']
];

export const extracts = [
    ['Ashwagandha Ghanvati', 'अश्वगंधा घनवटी', ['Stress', 'Strength', 'Sleep'], '1 tab', 'Milk', 'दूध के साथ'],
    ['Guduchi Ghanvati', 'गिलोय घनवटी', ['Fever', 'Immunity', 'Detox'], '1 tab', 'Water', 'पानी के साथ'],
    ['Tulsi Ghanvati', 'तुलसी घनवटी', ['Cold', 'Cough', 'Immunity'], '1 tab', 'Water', 'पानी के साथ'],
    ['Neem Ghanvati', 'नीम घनवटी', ['Skin', 'Diabetes', 'Blood'], '1 tab', 'Water', 'पानी के साथ'],
    ['Karela Ghanvati', 'करेला घनवटी', ['Diabetes', 'Sugar', 'Worms'], '1 tab', 'Water', 'पानी के साथ'],
    ['Jamun Ghanvati', 'जामुन घनवटी', ['Diabetes', 'Sugar', 'Diarrhea'], '1 tab', 'Water', 'पानी के साथ'],
    ['Methi Ghanvati', 'मेथी घनवटी', ['Diabetes', 'Joints', 'Pain'], '1 tab', 'Water', 'पानी के साथ'],
    ['Haldi Ghanvati', 'हल्दी घनवटी', ['Allergy', 'Skin', 'Immunity'], '1 tab', 'Milk', 'दूध के साथ'],
    ['Shilajit Ghanvati', 'शिलाजीत घनवटी', ['Energy', 'Aging', 'Vitality'], '1 tab', 'Milk', 'दूध के साथ'],
    ['Triphala Ghanvati', 'त्रिफला घनवटी', ['Detox', 'Eyes', 'Digestion'], '1 tab', 'Water', 'पानी के साथ'],
    ['Kutki Ghanvati', 'कुटकी घनवटी', ['Liver', 'Fever', 'Detox'], '1 tab', 'Water', 'पानी के साथ'],
    ['Chirata Ghanvati', 'चिरायता घनवटी', ['Blood', 'Skin', 'Fever'], '1 tab', 'Water', 'पानी के साथ'],
    ['Kalmegh Ghanvati', 'कालमेघ घनवटी', ['Liver', 'Antiviral', 'Fever'], '1 tab', 'Water', 'पानी के साथ'],
    ['Brahmi Ghanvati', 'ब्राह्मी घनवटी', ['Brain', 'Memory', 'Cooling'], '1 tab', 'Milk', 'दूध के साथ'],
    ['Shankhpushpi Ghanvati', 'शंखपुष्पी घनवटी', ['Brain', 'Sleep', 'Focus'], '1 tab', 'Milk', 'दूध के साथ'],
    ['Jatamansi Ghanvati', 'जटामांसे घनवटी', ['Sleep', 'BP', 'Relax'], '1 tab', 'Water', 'पानी के साथ'],
    ['Arjuna Ghanvati', 'अर्जुन घनवटी', ['Heart', 'BP', 'Chest'], '1 tab', 'Water', 'पानी के साथ'],
    ['Punarnava Ghanvati', 'पुनर्नवा घनवटी', ['Kidney', 'Swelling', 'Liver'], '1 tab', 'Water', 'पानी के साथ'],
    ['Gokshura Ghanvati', 'गोक्षुर घनवटी', ['Kidney', 'Prostate', 'Urine'], '1 tab', 'Water', 'पानी के साथ'],
    ['Manjistha Ghanvati', 'मंजिष्ठा घनवटी', ['Skin', 'Blood', 'Glow'], '1 tab', 'Water', 'पानी के साथ'],
    ['Shallaki Ghanvati', 'शल्लकी घनवटी', ['Joints', 'Pain', 'Arthritis'], '1 tab', 'Water', 'पानी के साथ'],
    ['Haritaki Ghanvati', 'हरीतकी घनवटी', ['Digestion', 'Gas', 'Cleansing'], '1 tab', 'Water', 'पानी के साथ'],
    ['Amla Ghanvati', 'आंवला घनवटी', ['Acidity', 'Hair', 'Eyes'], '1 tab', 'Water', 'पानी के साथ'],
    ['Bibhitaki Ghanvati', 'विभीतक घनवटी', ['Cough', 'Throat', 'Hair'], '1 tab', 'Water', 'पानी के साथ'],
    ['Moringa Ghanvati', 'सहजन घनवटी', ['Nutrition', 'Bones', 'BP'], '1 tab', 'Water', 'पानी के साथ'],
    ['Wheatgrass Ghanvati', 'व्हीटग्रास', ['Detox', 'Blood', 'Energy'], '1 tab', 'Water', 'पानी के साथ'],
    ['Spirulina Ghanvati', 'स्पिरुलिना', ['Protein', 'Energy', 'Immunity'], '1 tab', 'Water', 'पानी के साथ'],
    ['Garlic Ghanvati', 'लसून घनवटी', ['Heart', 'Gas', 'Cholesterol'], '1 tab', 'Water', 'पानी के साथ'],
    ['Ginger Ghanvati', 'अदरक घनवटी', ['Cold', 'Digestion', 'Pain'], '1 tab', 'Water', 'पानी के साथ'],
    ['Pippali Ghanvati', 'पिप्पली घनवटी', ['Lungs', 'Cold', 'Weight'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Maricha Ghanvati', 'कालीमिर्च', ['Cough', 'Fat', 'Throat'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Saunf Ghanvati', 'सौंफ घनवटी', ['Digestion', 'Acid', 'Fresh'], '1 tab', 'Water', 'पानी के साथ'],
    ['Ajwain Ghanvati', 'अजवायन घनवटी', ['Gas', 'Pain', 'Colic'], '1 tab', 'Water', 'पानी के साथ'],
    ['Jeera Ghanvati', 'जीरा घनवटी', ['Digestion', 'Cooling', 'Weight'], '1 tab', 'Water', 'पानी के साथ'],
    ['Dhaniya Ghanvati', 'धनिया घनवटी', ['Thyroid', 'Heat', 'Burning'], '1 tab', 'Water', 'पानी के साथ'],
    ['Hing Ghanvati', 'हींग घनवटी', ['Gas', 'Bloating', 'Pain'], '1 tab', 'Water', 'पानी के साथ'],
    ['Dalchini Ghanvati', 'दालचीनी', ['Sugar', 'PCOS', 'Weight'], '1 tab', 'Water', 'पानी के साथ'],
    ['Elaichi Ghanvati', 'इलायची', ['Nausea', 'Vomit', 'Acid'], '1 tab', 'Chew', 'चबाएं'],
    ['Lavang Ghanvati', 'लौंग घनवटी', ['Tooth', 'Cough', 'Throat'], '1 tab', 'Chew', 'चबाएं'],
    ['Jaiphal Ghanvati', 'जायफल', ['Sleep', 'Diarrhea', 'Pain'], '1 tab', 'Milk', 'दूध के साथ'],
    ['Sarpagandha Ghanvati', 'सर्पगंधा', ['BP', 'Mind', 'Sleep'], '1 tab', 'Doctor', 'डॉक्टर'],
    ['Tagar Ghanvati', 'तगर', ['Sleep', 'Relax', 'Pain'], '1 tab', 'Water', 'पानी के साथ'],
    ['Vacha Ghanvati', 'वचा', ['Mind', 'Speech', 'Focus'], '1 tab', 'Honey', 'शहद के साथ']
];

export const arks = [
    ['Ark Ajwain', 'अर्क अजवायन', ['Gas', 'Colic', 'Pain'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Saunf', 'अर्क सौंफ', ['Digestion', 'Colic', 'Acid'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Gulab', 'अर्क गुलाब', ['Cooling', 'Eyes', 'Stress'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Pudina', 'अर्क पुदीना', ['Gas', 'Nausea', 'Vomit'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Mako', 'अर्क मकोय', ['Liver', 'Spleen', 'Swelling'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Kasni', 'अर्क कासनी', ['Liver', 'Kidney', 'Detox'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Dashmool', 'अर्क दशमूल', ['Pain', 'Vata', 'Post-natal'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Shatavari', 'अर्क शतावरी', ['Women', 'Cooling', 'Milk'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Ashwagandha', 'अर्क अश्वगंधा', ['Stress', 'Strength'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Brahmi', 'अर्क ब्राह्मी', ['Brain', 'Memory'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Tulsi', 'अर्क तुलसी', ['Cold', 'Cough', 'Immunity'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Neem', 'अर्क नीम', ['Skin', 'Blood', 'Diabetes'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Giloy', 'अर्क गिलोय', ['Fever', 'Immunity'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Punarnava', 'अर्क पुनर्नवा', ['Kidney', 'Swelling'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Gokshura', 'अर्क गोक्षुर', ['Kidney', 'Urine'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Harad', 'अर्क हरड़', ['Digestion', 'Detox'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Amla', 'अर्क आंवला', ['Acid', 'Vitamin C'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Jeera', 'अर्क जीरा', ['Digestion', 'Cooling'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Dhaniya', 'अर्क धनिया', ['Heat', 'Thyroid'], '10ml', 'Water', 'पानी के साथ'],
    ['Ark Dalchini', 'अर्क दालचीनी', ['Sugar', 'Metabolism'], '10ml', 'Water', 'पानी के साथ']
];

export const classicalMix = [
    ['Saptamrit Lauh', 'सप्तामृत लौह', ['Eyes', 'Hair', 'Vision'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Dhatri Lauh', 'धात्री लौह', ['Anemia', 'Acidity', 'Eyes'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Navayasa Lauh', 'नवायस लौह', ['Anemia', 'Liver', 'Heart'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Punarnavadi Mandoor', 'पुनर्नवादि मंडूर', ['Anemia', 'Swelling', 'Kidney'], '1 tab', 'Water', 'पानी के साथ'],
    ['Vidangadi Lauh', 'विडंगादि लौह', ['Worms', 'Obesity', 'Jaundice'], '1 tab', 'Water', 'पानी के साथ'],
    ['Tapyadi Lauh', 'ताप्यादि लौह', ['Liver', 'Anemia', 'Periods'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Pradarantak Lauh', 'प्रदरांतक लौह', ['Leucorrhea', 'Periods', 'Pain'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Sarvajwarhar Lauh', 'सर्वज्वरहर लौह', ['All Fevers', 'Weakness'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Krimikuthar Ras', 'कृमिक कुठार', ['Worms', 'Itching', 'Stomach'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Amvatari Ras', 'आमवातारी रस', ['Rheumatoid', 'Joints', 'Pain'], '1 tab', 'Warm Water', 'गर्म पानी'],
    ['Shvas Kuthar Ras', 'श्वास कुठार', ['Asthma', 'Cough', 'Breath'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Kaphaketu Ras', 'कफकेतु रस', ['Cold', 'Sinus', 'Headache'], '1 tab', 'Ginger', 'अदरक रस'],
    ['Tribhuvan Kirti', 'त्रिभुवन कीर्ति', ['Fever', 'Flu', 'Body Pain'], '1 tab', 'Ginger', 'अदरक रस'],
    ['Sanjivani Vati', 'संजीवनी वटी', ['Fever', 'Indigestion', 'Snake'], '1 tab', 'Ginger', 'अदरक रस'],
    ['Laxmi Vilas Ras', 'लक्ष्मी विलास', ['Cold', 'Lungs', 'Weakness'], '1 tab', 'Betel Leaf', 'पान के साथ'],
    ['Naradiya Laxmi Vilas', 'नारदीय लक्ष्मी', ['Sinus', 'Fistula', 'Skin'], '1 tab', 'Water', 'पानी के साथ'],
    ['Mahalakshmi Vilas', 'महालक्ष्मी विलास', ['Lungs', 'Heart', 'Strength'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Vat Gaja Ankush', 'वात गजा अंकुश', ['Severe Pain', 'Sciatica'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Maha Yograj Guggulu', 'महायोगराज', ['Chronic Pain', 'Vata'], '2 tabs', 'Warm Water', 'गर्म पानी'],
    ['Yograj Guggulu', 'योगराज गुग्गुलु', ['Joints', 'Gas', 'Pain'], '2 tabs', 'Warm Water', 'गर्म पानी'],
    ['Kanchanar Guggulu', 'कांचनार', ['Thyroid', 'Tumor', 'Cyst'], '2 tabs', 'Water', 'पानी के साथ'],
    ['Triphala Guggulu', 'त्रिफला गुग्गुलु', ['Piles', 'Fat', 'Fistula'], '2 tabs', 'Warm Water', 'गर्म पानी'],
    ['Kaishore Guggulu', 'कैशोर गुग्गुलु', ['Uric Acid', 'Skin', 'Blood'], '2 tabs', 'Water', 'पानी के साथ'],
    ['Simhanad Guggulu', 'सिंहनाद गुग्गुलु', ['Rheumatoid', 'Detox', 'Pain'], '2 tabs', 'Warm Water', 'गर्म पानी'],
    ['Gokshuradi Guggulu', 'गोक्षुरादि', ['Urinary', 'Kidney', 'Stone'], '2 tabs', 'Water', 'पानी के साथ'],
    ['Punarnavadi Guggulu', 'पुनर्नवादि', ['Swelling', 'Kidney', 'Joints'], '2 tabs', 'Water', 'पानी के साथ'],
    ['Lakshadi Guggulu', 'लाक्षादि', ['Bone Fracture', 'Calcium'], '2 tabs', 'Milk', 'दूध के साथ'],
    ['Abha Guggulu', 'आभा गुग्गुलु', ['Fracture', 'Pain', 'Bone'], '2 tabs', 'Milk', 'दूध के साथ'],
    ['Medohar Guggulu', 'मेदोहर', ['Obesity', 'Fat', 'Cholesterol'], '2 tabs', 'Warm Water', 'गर्म पानी'],
    ['Navaka Guggulu', 'नवक गुग्गुलु', ['Obesity', 'Rheumatism'], '2 tabs', 'Warm Water', 'गर्म पानी'],
    ['Saptavimshati Guggulu', 'सप्तविंशति', ['Fistula', 'Skin', 'Infection'], '2 tabs', 'Water', 'पानी के साथ'],
    ['Trayodashang Guggulu', 'त्रयोदशांग', ['Sciatica', 'Back Pain', 'Pelvis'], '2 tabs', 'Warm Water', 'गर्म पानी'],
    ['Avipattikar Churna', 'अविपत्तिकर', ['Acidity', 'Constipation'], '1 tsp', 'Water', 'पानी के साथ'],
    ['Hingvastak Churna', 'हिंग्वाष्टक', ['Gas', 'Bloating', 'Indigestion'], '1 tsp', 'Ghee', 'घी के साथ'],
    ['Lavan Bhaskar', 'लवण भास्कर', ['Gas', 'Appetite', 'Taste'], '1 tsp', 'Buttermilk', 'छाछ के साथ'],
    ['Trikatu Churna', 'त्रिकटु', ['Metabolism', 'Cold', 'Cough'], '1/4 tsp', 'Honey', 'शहद के साथ'],
    ['Triphala Churna', 'त्रिफला', ['Constipation', 'Eyes', 'Detox'], '1 tsp', 'Warm Water', 'गर्म पानी'],
    ['Sitopaladi Churna', 'सितोपलादि', ['Cough', 'Flu', 'Hands Burning'], '1 tsp', 'Honey', 'शहद के साथ'],
    ['Talisadi Churna', 'तालीसादि', ['Cough', 'Cold', 'Appetite'], '1 tsp', 'Honey', 'शहद के साथ'],
    ['Pushyanuga Churna', 'पुष्यानुग', ['Bleeding', 'Leucorrhea'], '1 tsp', 'Rice Water', 'चावल पानी'],
    ['Gangadhar Churna', 'गंगाधर', ['Diarrhea', 'IBS', 'Dysentery'], '1 tsp', 'Buttermilk', 'छाछ के साथ'],
    ['Bilvadi Churna', 'बिल्वादि', ['Diarrhea', 'Poison', 'Gut'], '1 tsp', 'Water', 'पानी के साथ'],
    ['Dadimashtak Churna', 'दाडिमाष्टक', ['Diarrhea', 'Gas', 'Taste'], '1 tsp', 'Water', 'पानी के साथ'],
    ['Ajmodadi Churna', 'अजमोदादि', ['Joints', 'Pain', 'Swelling'], '1 tsp', 'Warm Water', 'गर्म पानी'],
    ['Panchsakar Churna', 'पंचसकार', ['Constipation', 'Gas', 'Piles'], '1 tsp', 'Warm Water', 'गर्म पानी'],
    ['Shivakshar Pachan', 'शिवाक्षार', ['Gas', 'Appetite', 'Acid'], '1 tsp', 'Water', 'पानी के साथ'],
    ['Mahasudarshan', 'महासुदर्शन', ['Fever', 'Liver', 'Infection'], '1 tsp', 'Water', 'पानी के साथ'],
    ['Chopchiniyadi', 'चोपचीनीयादि', ['Syphilis', 'Skin', 'Ulcer'], '1 tsp', 'Honey', 'शहद के साथ'],
    ['Ashwagandhadi', 'अश्वगंधादि', ['Strength', 'Sperm', 'Energy'], '1 tsp', 'Milk', 'दूध के साथ'],
    ['Shatavaryadi', 'शतावर्यादि', ['Strength', 'Eyes', 'Sex'], '1 tsp', 'Milk', 'दूध के साथ'],
    ['Yastimadhu Churna', 'यष्टिमधु', ['Acid', 'Throat', 'Ulcer'], '1 tsp', 'Honey', 'शहद के साथ'],
    ['Mullaka Kshara', 'मूलक क्षार', ['Kidney Stone', 'Urine'], '500mg', 'Water', 'पानी के साथ'],
    ['Yava Kshara', 'यव क्षार', ['Prostate', 'Gas', 'Urine'], '500mg', 'Water', 'पानी के साथ'],
    ['Apamarga Kshara', 'अपामार्ग', ['Ear', 'Warts', 'Fistula'], 'External', 'Apply', 'लगाएं'],
    ['Bol Parpati', 'बोल पर्पटी', ['Bleeding', 'Piles', 'Periods'], '250mg', 'Honey', 'शहद के साथ'],
    ['Panchamrit Parpati', 'पंचामृत', ['Diarrhea', 'IBS', 'Gut'], '250mg', 'Buttermilk', 'छाछ'],
    ['Rasa Parpati', 'रस पर्पटी', ['IBS', 'Malabsorption'], '250mg', 'Buttermilk', 'छाछ'],
    ['Swarna Parpati', 'स्वर्ण पर्पटी', ['TB', 'Chronic IBS', 'Weakness'], '125mg', 'Honey', 'शहद के साथ'],
    ['Vijay Parpati', 'विजय पर्पटी', ['Fever', 'Diarrhea', 'Pain'], '125mg', 'Honey', 'शहद के साथ'],
    ['Kamdudha Ras', 'कामदुधा', ['Pitta', 'Acid', 'Heat'], '250mg', 'Water', 'पानी के साथ'],
    ['Sutshekhar Ras', 'सूतशेखर', ['Acid', 'Headache', 'Vomit'], '250mg', 'Honey', 'शहद के साथ'],
    ['Laghusutshekhar', 'लघुसूतशेखर', ['Acid', 'Gas', 'Headache'], '250mg', 'Water', 'पानी के साथ'],
    ['Shankha Vati', 'शंख वटी', ['Gas', 'Pain', 'Acid'], '2 tabs', 'Warm Water', 'गर्म पानी'],
    ['Chitrakadi Vati', 'चित्रकादि', ['Digestion', 'IBS', 'Ama'], '2 tabs', 'Buttermilk', 'छाछ'],
    ['Agnitundi Vati', 'अग्नितुंडी', ['Indigestion', 'Gas', 'Pain'], '1 tab', 'Warm Water', 'गर्म पानी'],
    ['Lashunadi Vati', 'लसुनादि', ['Gas', 'Diarrhea', 'Cholesterol'], '2 tabs', 'Warm Water', 'गर्म पानी'],
    ['Khadiradi Vati', 'खदिरादि', ['Throat', 'Mouth', 'Teeth'], '1 tab', 'Chew', 'चूसें'],
    ['Lavangadi Vati', 'लवंगादि', ['Cough', 'Cold', 'Throat'], '1 tab', 'Chew', 'चूसें'],
    ['Eladi Vati', 'एलादि', ['Cough', 'Voice', 'Cold'], '1 tab', 'Chew', 'चूसें'],
    ['Vyoshadi Vati', 'व्योषादि', ['Cold', 'Runny Nose', 'Sinus'], '1 tab', 'Honey', 'शहद के साथ'],
    ['Prabhakar Vati', 'प्रभाकर', ['Heart', 'BP', 'Strength'], '1 tab', 'Arjuna Tea', 'अर्जुन क्वाथ'],
    ['Hridyamrit Vati', 'हृद्यामृत', ['Heart', 'Blockage', 'Cholesterol'], '1 tab', 'Water', 'पानी के साथ'],
    ['Medha Vati', 'मेधा वटी', ['Brain', 'Memory', 'Stress'], '2 tabs', 'Milk', 'दूध के साथ'],
    ['Madhunashini', 'मधुनाशिनी', ['Diabetes', 'Sugar', 'Nerves'], '2 tabs', 'Water', 'पानी के साथ'],
    ['Immunogrit', 'इम्युनोग्रिट', ['Immunity', 'Weakness', 'Energy'], '2 tabs', 'Water', 'पानी के साथ'],
    ['Swasari Vati', 'श्वासारि', ['Asthma', 'Cough', 'Cold'], '2 tabs', 'Warm Water', 'गर्म पानी'],
    ['Coronil', 'कोरोनिल', ['Fever', 'Flu', 'Virus'], '2 tabs', 'Water', 'पानी के साथ'],
    ['Livogrit', 'लिवोग्रिट', ['Liver', 'Jaundice', 'Detox'], '2 tabs', 'Water', 'पानी के साथ'],
    ['Renogrit', 'रेनोग्रिट', ['Kidney', 'Failure', 'Creatinine'], '2 tabs', 'Water', 'पानी के साथ'],
    ['Peedanil', 'पीडानिल', ['Pain', 'Joints', 'Inflammation'], '2 tabs', 'Water', 'पानी के साथ'],
    ['Orthogrit', 'ऑर्थोग्रिट', ['Arthritis', 'Bone', 'Pain'], '2 tabs', 'Water', 'पानी के साथ'],
    ['Chandraprabha', 'चंद्रप्रभा', ['UTI', 'Weakness', 'Sugar'], '2 tabs', 'Water', 'पानी के साथ'],
    ['Kaisora', 'कैशोर', ['Skin', 'Gout', 'Acne'], '2 tabs', 'Water', 'पानी के साथ']
];
