export const pharmacyMedicines = [
    // --- PAIN RELIEF (25 ITEMS) ---
    { id: 1, name: "Panadol Advance 500mg", category: "Pain Relief", price: 120, dose: "15 Tablets", image: "BsCapsule", desc: "Fast-acting paracetamol for headache, fever, and muscle pain.", tags: ["Best Seller", "Fast Relief"] },
    { id: 2, name: "Brufen 400mg", category: "Pain Relief", price: 85, dose: "10 Tablets", image: "BsCapsule", desc: "Ibuprofen for inflammation, dental pain, and joint aches.", tags: ["Anti-inflammatory"] },
    { id: 3, name: "Voveran SR 100", category: "Pain Relief", price: 165, dose: "10 Tablets", image: "BsCapsule", desc: "Diclofenac for severe back pain and osteoarthritic discomfort.", tags: ["Joint Care"] },
    { id: 4, name: "Dolo 650", category: "Pain Relief", price: 30, dose: "15 Tablets", image: "BsCapsule", desc: "India's favorite fever fighter. High-dose Paracetamol.", tags: ["Fever Specialist"] },
    { id: 5, name: "Combiflam", category: "Pain Relief", price: 45, dose: "20 Tablets", image: "BsCapsule", desc: "Dual-action Ibuprofen & Paracetamol for intense body aches.", tags: ["Dual Action"] },
    { id: 6, name: "Aspirin 75mg", category: "Pain Relief", price: 15, dose: "14 Tablets", image: "BsCapsule", desc: "Low-dose aspirin for heart protection and blood thinning.", tags: ["Heart Safe"] },
    { id: 7, name: "Naproxen 250mg", category: "Pain Relief", price: 210, dose: "10 Tablets", image: "BsCapsule", desc: "Long-lasting relief for menstrual cramps and gout pain.", tags: ["Long Duration"] },
    { id: 8, name: "Meftal Spas", category: "Pain Relief", price: 55, dose: "10 Tablets", image: "BsCapsule", desc: "Specialized for stomach cramps and abdominal pain.", tags: ["Stomach Comfort"] },
    { id: 9, name: "Tramadol Neural", category: "Pain Relief", price: 420, dose: "10 Capsules", image: "BsCapsule", desc: "Potent analgesic for post-operative recovery support.", tags: ["Restricted"] },
    { id: 10, name: "Zerodol-P", category: "Pain Relief", price: 110, dose: "10 Tablets", image: "BsCapsule", desc: "Aceclofenac combination for acute shoulder and neck pain.", tags: ["Ortho Choice"] },
    { id: 11, name: "Dart Tablet", category: "Pain Relief", price: 25, dose: "10 Tablets", image: "BsCapsule", desc: "Caffeine-boosted paracetamol for migraine relief.", tags: ["Headache Expert"] },
    { id: 12, name: "Ultracet", category: "Pain Relief", price: 290, dose: "15 Tablets", image: "BsCapsule", desc: "Premium combination for chronic musculoskeletal pain.", tags: ["Clinical Grade"] },
    { id: 13, name: "Etoshine 90", category: "Pain Relief", price: 310, dose: "10 Tablets", image: "BsCapsule", desc: "Highly effective for rheumatoid arthritis flare-ups.", tags: ["Specialist Care"] },
    { id: 14, name: "Piroxicam Gel", category: "Pain Relief", price: 140, dose: "30g", image: "BsDropletFill", desc: "Topical application for instant local inflammation relief.", tags: ["External Use"] },
    { id: 15, name: "Moov Advanced Gel", category: "Pain Relief", price: 185, dose: "50g", image: "BsDropletFill", desc: "Ayurvedic-clinical blend for back and neck spasms.", tags: ["Ayurvedic Base"] },
    { id: 16, name: "Volini Spray", category: "Pain Relief", price: 220, dose: "60ml", image: "BsLightningFill", desc: "Instant spray for sports injuries and pulled muscles.", tags: ["Sports Essential"] },
    { id: 17, name: "Saridon Ultra", category: "Pain Relief", price: 40, dose: "10 Tablets", image: "BsCapsule", desc: "Triple action formula for stubborn headaches.", tags: ["Classic Choice"] },
    { id: 18, name: "Sumatriptan 50", category: "Pain Relief", price: 520, dose: "2 Tablets", image: "BsCapsule", desc: "Targeted migraine treatment for severe attacks.", tags: ["Migraine Specialist"] },
    { id: 19, name: "Lignocaine Jelly", category: "Pain Relief", price: 75, dose: "30g", image: "BsDropletFill", desc: "Local anesthetic for superficial minor burns and stings.", tags: ["Topic Anesthetic"] },
    { id: 20, name: "Dynapar AQ", category: "Pain Relief", price: 155, dose: "1ml Injection", image: "BsDropletFill", desc: "Rapid action diclofenac for emergency pain control.", tags: ["Clinical Only"] },
    { id: 21, name: "Spasmo-Proxyvon", category: "Pain Relief", price: 130, dose: "8 Capsules", image: "BsCapsule", desc: "Strong spasmodic relief for severe intestinal pain.", tags: ["Prescription Only"] },
    { id: 22, name: "Ketoflam 10mg", category: "Pain Relief", price: 190, dose: "10 Tablets", image: "BsCapsule", desc: "Effective post-dental extraction analgesia.", tags: ["Dental Care"] },
    { id: 23, name: "Caldic-P", category: "Pain Relief", price: 65, dose: "15 Tablets", image: "BsCapsule", desc: "Calcium-friendly paracetamol for pediatric care.", tags: ["Mild"] },
    { id: 24, name: "Hifenac-P", category: "Pain Relief", price: 95, dose: "10 Tablets", image: "BsCapsule", desc: "Anti-arthritic combination for elderly patients.", tags: ["Senior Care"] },
    { id: 25, name: "Zandu Balm Ultra", category: "Pain Relief", price: 110, dose: "25ml", image: "BsDropletFill", desc: "High-menthol relief for cold-induced headaches.", tags: ["Natural Power"] },

    // --- WELLNESS & VITAMINS (40 ITEMS) ---
    { id: 26, name: "Becosules Z", category: "Wellness", price: 55, dose: "20 Capsules", image: "BsCapsule", desc: "B-Complex with Vitamin C and Zinc for energy & mouth ulcers.", tags: ["Daily Essential"] },
    { id: 27, name: "Revital H", category: "Wellness", price: 310, dose: "30 Capsules", image: "BsCapsule", desc: "Ginseng-based daily supplement for physical & mental agility.", tags: ["Men's Health"] },
    { id: 28, name: "Shelcal 500", category: "Wellness", price: 145, dose: "15 Tablets", image: "BsCapsule", desc: "Calcium and Vitamin D3 for bone strength and density.", tags: ["Bone Health"] },
    { id: 29, name: "Neurobion Forte", category: "Wellness", price: 40, dose: "30 Tablets", image: "BsCapsule", desc: "Nerve nourishment for numbness and burning sensations.", tags: ["Vitamin B12"] },
    { id: 30, name: "Uprise D3 60K", category: "Wellness", price: 180, dose: "4 Capsules", image: "BsCapsule", desc: "Weekly dose of Vitamin D3 for immunity and osteoporosis.", tags: ["High Dose", "Immunity"] },
    { id: 31, name: "Limcee 500mg", category: "Wellness", price: 30, dose: "15 Tablets", image: "BsCapsule", desc: "Chewable Vitamin C for skin health and scurvy prevention.", tags: ["Skin Health"] },
    { id: 32, name: "Evion 400", category: "Wellness", price: 350, dose: "10 Capsules", image: "BsCapsule", desc: "Vitamin E for luxury hair growth and anti-aging antioxidant support.", tags: ["Premium Beauty"] },
    { id: 33, name: "Seven Seas Cod Liver", category: "Wellness", price: 480, dose: "100 Capsules", image: "BsCapsule", desc: "Pure Omega-3 and Vitamin A/D for joint and eye health.", tags: ["Kid's Choice"] },
    { id: 34, name: "Horlicks Health Plus", category: "Wellness", price: 650, dose: "500g Jar", image: "BsDropletFill", desc: "Clinically proven to make kids taller, stronger, sharper.", tags: ["Family Pack"] },
    { id: 35, name: "Zincovit Tablet", category: "Wellness", price: 115, dose: "15 Tablets", image: "BsCapsule", desc: "Multi-mineral multivitamin for speedy disease recovery.", tags: ["Post-Viral Care"] },
    { id: 36, name: "Supradyn Daily", category: "Wellness", price: 60, dose: "15 Tablets", image: "BsCapsule", desc: "Complete daily nutrition for active busy lifestyles.", tags: ["All-in-One"] },
    { id: 37, name: "Pudin Hara Pearls", category: "Wellness", price: 25, dose: "10 Pearls", image: "BsDropletFill", desc: "Ayurvedic relief for acidity, gas, and indigestion.", tags: ["Natural Digestion"] },
    { id: 38, name: "Ensure Adult Nutrition", category: "Wellness", price: 1450, dose: "400g Jar", image: "BsDropletFill", desc: "Complete balanced nutrition with high protein and minerals.", tags: ["Elderly Nutri"] },
    { id: 39, name: "Women's Horlicks", category: "Wellness", price: 580, dose: "400g Refill", image: "BsDropletFill", desc: "Specifically designed for bone health and iron needs in women.", tags: ["Women's Specialized"] },
    { id: 40, name: "Himalaya Ashwagandha", category: "Wellness", price: 220, dose: "60 Tablets", image: "BsCapsule", desc: "Pure herb for stress relief and vitality enhancement.", tags: ["Stress Management"] },
    { id: 41, name: "Dabur Chyawanprash", category: "Wellness", price: 390, dose: "1kg", image: "BsDropletFill", desc: "Ancient Ayurvedic immunity booster for the whole family.", tags: ["Traditional"] },
    { id: 42, name: "Biotin Gold 10mg", category: "Wellness", price: 850, dose: "60 Tablets", image: "BsCapsule", desc: "High-potency biotin for thick hair and strong nails.", tags: ["Hair Specialist"] },
    { id: 43, name: "Magnesium Complex", category: "Wellness", price: 720, dose: "60 Tablets", image: "BsCapsule", desc: "Supports nerve function and reduces muscle cramps.", tags: ["Deep Sleep Support"] },
    { id: 44, name: "Probiotic 50B CFU", category: "Wellness", price: 1100, dose: "30 Capsules", image: "BsCapsule", desc: "Advanced gut health support with multi-strain bacteria.", tags: ["Gut Specialist"] },
    { id: 45, name: "Iron XT Folic Acid", category: "Wellness", price: 190, dose: "30 Tablets", image: "BsCapsule", desc: "Blood builder for anemia and pregnancy support.", tags: ["Anemia Cure"] },
    { id: 46, name: "Fish Oil Elite 1500", category: "Wellness", price: 1850, dose: "90 Softgels", image: "BsCapsule", desc: "High EPA/DHA ratio for elite heart and brain performance.", tags: ["Brain Power"] },
    { id: 47, name: "Melatonin 3mg", category: "Wellness", price: 550, dose: "60 Tablets", image: "BsCapsule", desc: "Natural sleep aid for jet lag and insomnia support.", tags: ["Restful Sleep"] },
    { id: 48, name: "Glucosamine Chondroitin", category: "Wellness", price: 1250, dose: "60 Tablets", image: "BsCapsule", desc: "Maximum joint support and flexibility enhancer.", tags: ["Mobility"] },
    { id: 49, name: "Liver Detox 360", category: "Wellness", price: 950, dose: "60 Capsules", image: "BsCapsule", desc: "Milk Thistle based blend for heavy metal detox.", tags: ["Liver Care"] },
    { id: 50, name: "Turmeric Curcumin", category: "Wellness", price: 680, dose: "60 Capsules", image: "BsCapsule", desc: "Natural anti-inflammatory with high piperine absorption.", tags: ["Superfood"] },
    { id: 51, name: "Elderberry Syrup", category: "Wellness", price: 890, dose: "250ml", image: "BsDropletFill", desc: "Potent antioxidant syrup for seasonal flu defense.", tags: ["Anti-Viral"] },
    { id: 52, name: "Spirulina Organic", category: "Wellness", price: 420, dose: "100 Tablets", image: "BsCapsule", desc: "nutrient-dense blue-green algae super supplement.", tags: ["Vegan Protein"] },
    { id: 53, name: "Collagen Peptides", category: "Wellness", price: 2100, dose: "300g Powder", image: "BsDropletFill", desc: "Type I & III bovine collagen for skin elasticity.", tags: ["Anti-Aging"] },
    { id: 54, name: "Garlic Oil 500mg", category: "Wellness", price: 380, dose: "100 Softgels", image: "BsCapsule", desc: "Supports cardiovascular health and normal BP levels.", tags: ["Heart Support"] },
    { id: 55, name: "Apple Cider Vinegar", category: "Wellness", price: 650, dose: "500ml", image: "BsDropletFill", desc: "Organic ACV with 'The Mother' for metabolism and weight.", tags: ["Metabolism"] },
    { id: 56, name: "Karela Jamun Juice", category: "Wellness", price: 280, dose: "1L", image: "BsDropletFill", desc: "Blood sugar regulator for pre-diabetic management.", tags: ["Natural Sugar Control"] },
    { id: 57, name: "Safi Blood Purifier", category: "Wellness", price: 195, dose: "500ml", image: "BsDropletFill", desc: "Herbal blend for acne-free clear skin from within.", tags: ["Acne Solution"] },
    { id: 58, name: "Amla Juice Ultra", category: "Wellness", price: 240, dose: "1L", image: "BsDropletFill", desc: "Rich source of Vitamin C for digestive wellness.", tags: ["Digestion"] },
    { id: 59, name: "L-Carnitine 1000", category: "Wellness", price: 1350, dose: "60 Tablets", image: "BsCapsule", desc: "Fat metabolizer for gym performance and energy.", tags: ["Gym Support"] },
    { id: 60, name: "Pre-Workout Neural", category: "Wellness", price: 1950, dose: "300g", image: "BsLightningFill", desc: "Explosive energy and focus for heavy workouts.", tags: ["Elite Energy"] },
    { id: 61, name: "Casein Protein Night", category: "Wellness", price: 3400, dose: "1kg", image: "BsDropletFill", desc: "Slow-digesting protein for overnight muscle repair.", tags: ["Recovery"] },
    { id: 62, name: "Creatine Monohydrate", category: "Wellness", price: 1100, dose: "250g", image: "BsLightningFill", desc: "Pure micronized creatine for power and volume.", tags: ["Strength"] },
    { id: 63, name: "BCAA 2:1:1 Matrix", category: "Wellness", price: 1650, dose: "30 Servings", image: "BsDropletFill", desc: "Intra-workout hydration and muscle endurance.", tags: ["Endurance"] },
    { id: 64, name: "Mass Gainer Gold", category: "Wellness", price: 2800, dose: "2kg", image: "BsDropletFill", desc: "High-calorie formula for hard gainers.", tags: ["Bulking"] },
    { id: 65, name: "Multivitamin Gummies", category: "Wellness", price: 450, dose: "30 Gummies", image: "BsMagic", desc: "Fun-to-eat vitamins for kids with 12 essential nutrients.", tags: ["Kid's Daily"] },

    // --- ANTIBIOTICS (15 ITEMS - ALL PRESCRIPTION REQ) ---
    { id: 66, name: "Augmentin 625 DUO", category: "Antibiotics", price: 210, dose: "10 Tablets", image: "BsCapsule", desc: "Amoxycillin and Potassium Clavulanate for lung and ear infections.", tags: ["Prescription Required", "Wide Spectrum"] },
    { id: 67, name: "Azithral 500", category: "Antibiotics", price: 125, dose: "3 Tablets", image: "BsCapsule", desc: "Azithromycin for throat infections and common flu complications.", tags: ["3 Day Course"] },
    { id: 68, name: "Taxim-O 200", category: "Antibiotics", price: 180, dose: "10 Tablets", image: "BsCapsule", desc: "Cefixime for urinary tract and respiratory infections.", tags: ["UTI Expert"] },
    { id: 69, name: "Cifran 500", category: "Antibiotics", price: 65, dose: "10 Tablets", image: "BsCapsule", desc: "Ciprofloxacin for skin, bone, and joint bacterial infections.", tags: ["Skin Infection"] },
    { id: 70, name: "Norflox TZ", category: "Antibiotics", price: 95, dose: "10 Tablets", image: "BsCapsule", desc: "Targeted for stomach infections and loose motions.", tags: ["Stomach Expert"] },
    { id: 71, name: "Zifi 200", category: "Antibiotics", price: 115, dose: "10 Tablets", image: "BsCapsule", desc: "Effective cephalosporin for typhoid and general fever.", tags: ["Typhoid Care"] },
    { id: 72, name: "Metrogyl 400", category: "Antibiotics", price: 25, dose: "15 Tablets", image: "BsCapsule", desc: "Antiprotozoal for dental and stomach parasitic issues.", tags: ["Parasite Defense"] },
    { id: 73, name: "Doxy-1 L-DR Forte", category: "Antibiotics", price: 140, dose: "10 capsules", image: "BsCapsule", desc: "Doxycycline with Lactic Acid for acne and viral fever.", tags: ["Acne Antibiotic"] },
    { id: 74, name: "Clavam 625", category: "Antibiotics", price: 230, dose: "10 Tablets", image: "BsCapsule", desc: "Premium Amoxiclav for resistant bacterial strains.", tags: ["Highly Potent"] },
    { id: 75, name: "Oflox 200", category: "Antibiotics", price: 80, dose: "10 Tablets", image: "BsCapsule", desc: "Ofloxacin for pelvic and lower respiratory infections.", tags: ["Clinical Choice"] },
    { id: 76, name: "Levoflox 500", category: "Antibiotics", price: 110, dose: "10 Tablets", image: "BsCapsule", desc: "Levofloxacin for acute bronchitis and pneumonia.", tags: ["Lungs Specialist"] },
    { id: 77, name: "Roxid 150", category: "Antibiotics", price: 165, dose: "10 Tablets", image: "BsCapsule", desc: "Roxithromycin for upper respiratory tract infections.", tags: ["ENT Priority"] },
    { id: 78, name: "Sporidex 500", category: "Antibiotics", price: 340, dose: "10 Capsules", image: "BsCapsule", desc: "Cephalexin for deep skin and soft tissue wound healing.", tags: ["Wound Specialist"] },
    { id: 79, name: "Bactrim DS", category: "Antibiotics", price: 45, dose: "10 Tablets", image: "BsCapsule", desc: "Sulfamethoxazole for multiple bacterial prophylaxis.", tags: ["Old School Power"] },
    { id: 80, name: "Monocef-O 200", category: "Antibiotics", price: 195, dose: "10 Tablets", image: "BsCapsule", desc: "Advanced Cefpodoxime for critical fever management.", tags: ["New Gen Pharma"] },

    // --- CHRONIC CARE (60 ITEMS) ---
    // Diabetes (20 Items)
    { id: 81, name: "Glycomet GP 1/500", category: "Chronic Care", price: 95, dose: "15 Tablets", image: "BsCapsule", desc: "Metformin + Glimepiride for Type 2 Diabetes management.", tags: ["Sugar Control"] },
    { id: 82, name: "Janumet 50/500", category: "Chronic Care", price: 1250, dose: "28 Tablets", image: "BsCapsule", desc: "Premium Sitagliptin combination for post-meal sugar spikes.", tags: ["Advanced Diabetes"] },
    { id: 83, name: "Lantus Solostar", category: "Chronic Care", price: 2850, dose: "3ml Pen", image: "BsDropletFill", desc: "Long-acting insulin glargine injection for 24hr basal control.", tags: ["Insulin Pen"] },
    { id: 84, name: "Galvus Met 50/1000", category: "Chronic Care", price: 1400, dose: "15 Tablets", image: "BsCapsule", desc: "Vildagliptin therapy for optimal HbA1c control.", tags: ["Consistent Hub"] },
    { id: 85, name: "Voglibose 0.3mg", category: "Chronic Care", price: 110, dose: "10 Tablets", image: "BsCapsule", desc: "Prevents high blood sugar after meals.", tags: ["Post-Meal Guard"] },
    { id: 86, name: "Humalog Mix 50/50", category: "Chronic Care", price: 1150, dose: "Kartridge", image: "BsDropletFill", desc: "Rapid and intermediate acting insulin mix.", tags: ["Rapid Control"] },
    { id: 87, name: "Jardiance 10mg", category: "Chronic Care", price: 2100, dose: "10 Tablets", image: "BsCapsule", desc: "SGLT2 inhibitor for heart protection in diabetics.", tags: ["Cardio-Diabetic"] },
    { id: 88, name: "Forxiga 10mg", category: "Chronic Care", price: 1850, dose: "28 Tablets", image: "BsCapsule", desc: "Advanced glucose excretion through urinary channel.", tags: ["Kidney Safe"] },
    { id: 89, name: "Teneligliptin 20mg", category: "Chronic Care", price: 130, dose: "15 Tablets", image: "BsCapsule", desc: "Affordable DPP4 inhibitor for daily glycemic balance.", tags: ["Best Value"] },
    { id: 90, name: "Pioglitazone 15mg", category: "Chronic Care", price: 65, dose: "10 Tablets", image: "BsCapsule", desc: "Improves insulin sensitivity in skeletal muscle.", tags: ["Sensitivity Boost"] },
    { id: 91, name: "Glynase XL 5", category: "Chronic Care", price: 40, dose: "10 Tablets", image: "BsCapsule", desc: "Extended release glipizide for stable sugar levels.", tags: ["Stable Release"] },
    { id: 92, name: "NovoMix 30 FlexPen", category: "Chronic Care", price: 1450, dose: "3ml Pen", image: "BsDropletFill", desc: "Convenient insulin delivery for busy lifestyles.", tags: ["Mobile Insulin"] },
    { id: 93, name: "Zita Met 50/500", category: "Chronic Care", price: 320, dose: "15 Tablets", image: "BsCapsule", desc: "Effective Gliptin-Metformin for weight-neutral control.", tags: ["Weight Safe"] },
    { id: 94, name: "Rybelsus 7mg", category: "Chronic Care", price: 9200, dose: "10 Tablets", image: "BsCapsule", desc: "Revolutionary ORAL Semaglutide for metabolic health.", tags: ["Elite Tech"] },
    { id: 95, name: "Diamicron XR 60", category: "Chronic Care", price: 420, dose: "15 Tablets", image: "BsCapsule", desc: "Protects beta cells while managing glucose levels.", tags: ["Beta Cell Care"] },
    { id: 96, name: "Accu-Chek Active Strips", category: "Chronic Care", price: 950, dose: "50 Strips", image: "BsActivity", desc: "High-precision testing strips for home monitoring.", tags: ["Home Diagnostic"] },
    { id: 97, name: "FreeStyle Libre Sensor", category: "Chronic Care", price: 4500, dose: "1 Unit", image: "BsActivity", desc: "Continuous Glucose Monitor (14-day tracking).", tags: ["No Finger Prick"] },
    { id: 98, name: "Metformin 1000 SR", category: "Chronic Care", price: 85, dose: "15 Tablets", image: "BsCapsule", desc: "Pure insulin sensitizer for steady-state control.", tags: ["Essential"] },
    { id: 99, name: "Glavus 50", category: "Chronic Care", price: 580, dose: "15 Tablets", image: "BsCapsule", desc: "Vildagliptin monotherapy for kidney-impaired patients.", tags: ["Gentle Flow"] },
    { id: 100, name: "Bydureon BCise", category: "Chronic Care", price: 15400, dose: "Auto-Injector", image: "BsHandIndexThumb", desc: "Once-weekly GLP-1 injection for modern obesity/diabetes.", tags: ["Weekly Luxury"] },

    // Heart & BP (20 Items)
    { id: 101, name: "Telma 40", category: "Chronic Care", price: 210, dose: "15 Tablets", image: "BsCapsule", desc: "Telmisartan for essential hypertension management.", tags: ["BP Specialist"] },
    { id: 102, name: "Amlokind 5", category: "Chronic Care", price: 25, dose: "15 Tablets", image: "BsCapsule", desc: "Calcium channel blocker for artery relaxation.", tags: ["Artery Care"] },
    { id: 103, name: "Rosuvas 10", category: "Chronic Care", price: 280, dose: "15 Tablets", image: "BsCapsule", desc: "Rosuvastatin for high cholesterol and plaque prevention.", tags: ["Lipid Lowering"] },
    { id: 104, name: "Clopilet 75", category: "Chronic Care", price: 145, dose: "15 Tablets", image: "BsCapsule", desc: "Prevents blood clots after heart stent or stroke.", tags: ["Blood Thinning"] },
    { id: 105, name: "Metoprolol XL 50", category: "Chronic Care", price: 110, dose: "15 Tablets", image: "BsCapsule", desc: "Beta-blocker to control heart rate and rhythm.", tags: ["Rate Control"] },
    { id: 106, name: "Atorva 20", category: "Chronic Care", price: 230, dose: "15 Tablets", image: "BsCapsule", desc: "Standard cholesterol-lowering statin for long-term safety.", tags: ["Longevity"] },
    { id: 107, name: "Ramipril 5mg", category: "Chronic Care", price: 75, dose: "15 Tablets", image: "BsCapsule", desc: "ACE Inhibitor for heart failure and kidney protection.", tags: ["Organ Guard"] },
    { id: 108, name: "Concor 5", category: "Chronic Care", price: 195, dose: "10 Tablets", image: "BsCapsule", desc: "Highly selective Bisoprolol for steady heart function.", tags: ["Precision Cardio"] },
    { id: 109, name: "Dilzem SR 90", category: "Chronic Care", price: 165, dose: "10 Tablets", image: "BsCapsule", desc: "Controls chronic chest pain (Angina) effectively.", tags: ["Chest Pain Relief"] },
    { id: 110, name: "Lasix 40mg", category: "Chronic Care", price: 10, dose: "15 Tablets", image: "BsCapsule", desc: "Water pill for edema and rapid BP drops.", tags: ["Diuretic"] },
    { id: 111, name: "Ecosprin Gold 10", category: "Chronic Care", price: 155, dose: "10 Capsules", image: "BsCapsule", desc: "Statins + Antiplatelet for total stroke protection.", tags: ["Stroke Shield"] },
    { id: 112, name: "Entresto 100", category: "Chronic Care", price: 3400, dose: "14 Tablets", image: "BsCapsule", desc: "Advanced Sacubitril/Valsartan for heart failure recovery.", tags: ["Latest Science"] },
    { id: 113, name: "Sildura 8", category: "Chronic Care", price: 420, dose: "10 Tablets", image: "BsCapsule", desc: "Manages pulmonary hypertension (Lung-Heart BP).", tags: ["Lung Pressure"] },
    { id: 114, name: "Ivabrad 5", category: "Chronic Care", price: 290, dose: "10 Tablets", image: "BsCapsule", desc: "Lowers heart rate without affecting blood pressure.", tags: ["Pulse Regulator"] },
    { id: 115, name: "Cardace 2.5", category: "Chronic Care", price: 85, dose: "15 Tablets", image: "BsCapsule", desc: "Daily Ramipril for early-stage hypertension.", tags: ["Early Care"] },
    { id: 116, name: "Minipress XL 5", category: "Chronic Care", price: 680, dose: "30 Tablets", image: "BsCapsule", desc: "Alpha-blocker for resistant high BP and prostate.", tags: ["Dual Action BP"] },
    { id: 117, name: "Olmesartan 20", category: "Chronic Care", price: 140, dose: "10 Tablets", image: "BsCapsule", desc: "Effective for patients not responding to Telmisartan.", tags: ["Stronger ARB"] },
    { id: 118, name: "Zestril 10", category: "Chronic Care", price: 125, dose: "14 Tablets", image: "BsCapsule", desc: "Lisinopril for cardiovascular event prevention.", tags: ["Risk Reducer"] },
    { id: 119, name: "Repatha Injection", category: "Chronic Care", price: 18500, dose: "Auto-injector", image: "BsHandIndexThumb", desc: "Revolutionary biological for ultra-low cholesterol.", tags: ["The Ultimate Lipid Gear"] },
    { id: 120, name: "Nitrocontin 2.6", category: "Chronic Care", price: 190, dose: "30 Tablets", image: "BsCapsule", desc: "Sustained nitroglycerin for chronic angina patients.", tags: ["Angina Guardian"] },

    // Kidney, Thyroid & Others (20 Items)
    { id: 121, name: "Thyronorm 50mcg", category: "Chronic Care", price: 185, dose: "120 Tablets", image: "BsCapsule", desc: "Levothyroxine for low thyroid hormone replacement.", tags: ["Thyroid Specialist"] },
    { id: 122, name: "Eltroxin 100mcg", category: "Chronic Care", price: 160, dose: "100 Tablets", image: "BsCapsule", desc: "Classic thyroid management for daily metabolism.", tags: ["Metabolism Support"] },
    { id: 123, name: "Ketosteril", category: "Chronic Care", price: 8500, dose: "100 Tablets", image: "BsCapsule", desc: "Essential amino acids for Chronic Kidney Disease.", tags: ["Kidney Life"] },
    { id: 124, name: "Nefrosave", category: "Chronic Care", price: 680, dose: "10 Tablets", image: "BsCapsule", desc: "Protecting kidney function in diabetic patients.", tags: ["Protective"] },
    { id: 125, name: "Renolog", category: "Chronic Care", price: 520, dose: "10 Tablets", image: "BsCapsule", desc: "Phosphate binder for advanced renal dialysis patients.", tags: ["Renal Support"] },
    { id: 126, name: "Febuget 40", category: "Chronic Care", price: 115, dose: "10 Tablets", image: "BsCapsule", desc: "Reduces uric acid for gout and kidney stones.", tags: ["Uric Acid Cure"] },
    { id: 127, name: "Folvite 5mg", category: "Chronic Care", price: 45, dose: "45 Tablets", image: "BsCapsule", desc: "Folic acid for nerve health and pregnancy.", tags: ["Neurology"] },
    { id: 128, name: "Cebocap 500", category: "Chronic Care", price: 490, dose: "10 Capsules", image: "BsCapsule", desc: "Boosts brain blood flow and recovery from trauma.", tags: ["Brain Recovery"] },
    { id: 129, name: "Donep 5", category: "Chronic Care", price: 210, dose: "10 Tablets", image: "BsCapsule", desc: "Manages memory loss in Alzheimer's and Dementia.", tags: ["Memory Care"] },
    { id: 130, name: "Amantadine 100", category: "Chronic Care", price: 135, dose: "10 Tablets", image: "BsCapsule", desc: "For Parkinson's tremors and abnormal muscle movement.", tags: ["Parkinson's Support"] },
    { id: 131, name: "Levipil 500", category: "Chronic Care", price: 440, dose: "15 Tablets", image: "BsCapsule", desc: "Anti-seizure medication for epilepsy control.", tags: ["Epilepsy Expert"] },
    { id: 132, name: "Encorate Chrono 300", category: "Chronic Care", price: 115, dose: "15 Tablets", image: "BsCapsule", desc: "Stabilizes mood and prevents migraine/seizures.", tags: ["Mood Stabilizer"] },
    { id: 133, name: "Gardenal 30", category: "Chronic Care", price: 25, dose: "30 Tablets", image: "BsCapsule", desc: "Pherebarbitone for tranquilization and sleep.", tags: ["Neural Calmer"] },
    { id: 134, name: "Pacitane 2mg", category: "Chronic Care", price: 60, dose: "10 Tablets", image: "BsCapsule", desc: "Relieves muscle stiffness in Parkinson's patients.", tags: ["Smooth Movement"] },
    { id: 135, name: "Tegretol 200", category: "Chronic Care", price: 35, dose: "10 Tablets", image: "BsCapsule", desc: "Controls nerve pain (Trigeminal Neuralgia).", tags: ["Nerve Pain Stop"] },
    { id: 136, name: "Gabapentin 300", category: "Chronic Care", price: 280, dose: "10 Capsules", image: "BsCapsule", desc: "Calms overactive nerves in diabetic neuropathy.", tags: ["Diabetic Nerves"] },
    { id: 137, name: "Pregabalin 75 SR", category: "Chronic Care", price: 165, dose: "10 Tablets", image: "BsCapsule", desc: "Superior nerve pain relief for spinal issues.", tags: ["Spine Support"] },
    { id: 138, name: "Stemetil 5mg", category: "Chronic Care", price: 95, dose: "15 Tablets", image: "BsCapsule", desc: "Stops severe vomiting and severe vertigo.", tags: ["Vertigo Stop"] },
    { id: 139, name: "Vertin 16", category: "Chronic Care", price: 210, dose: "15 Tablets", image: "BsCapsule", desc: "Specialized for Meniere's disease and dizziness.", tags: ["Dizziness Specialist"] },
    { id: 140, name: "Serc 24mg", category: "Chronic Care", price: 480, dose: "10 Tablets", image: "BsCapsule", desc: "High-grade Betahistine for ear-balancing issues.", tags: ["Balance Recovery"] },

    // --- SKIN CARE (30 ITEMS) ---
    { id: 141, name: "Betnovate-N Cream", category: "Skin Care", price: 45, dose: "20g", image: "BsDropletFill", desc: "Antibacterial steroid for acute eczema and skin rashes.", tags: ["Skin Emergency"] },
    { id: 142, name: "Panderm +", category: "Skin Care", price: 85, dose: "15g", image: "BsDropletFill", desc: "Combined antifungal and antibacterial skin healer.", tags: ["Multi-Purpose"] },
    { id: 143, name: "Candid Dusting Powder", category: "Skin Care", price: 135, dose: "100g", image: "BsMagic", desc: "Clotrimazole for fungal infections and sweat-induced itching.", tags: ["Fungal Shield"] },
    { id: 144, name: "Lulifin Cream 50g", category: "Skin Care", price: 650, dose: "50g", image: "BsDropletFill", desc: "Potent Luliconazole for stubborn ringworm and athletes foot.", tags: ["High Potency"] },
    { id: 145, name: "Tretinoin 0.05% Gel", category: "Skin Care", price: 210, dose: "20g", image: "BsDropletFill", desc: "Clinical grade Vitamin A for acne and anti-aging spots.", tags: ["Dermatologist Choice"] },
    { id: 146, name: "Hydroquinone 4%", category: "Skin Care", price: 190, dose: "15g", image: "BsDropletFill", desc: "Skin lightening for hyperpigmentation and melasma.", tags: ["Beauty Clinical"] },
    { id: 147, name: "Mupirocin Ointment", category: "Skin Care", price: 280, dose: "5g", image: "BsDropletFill", desc: "Targeted antibiotic for bacterial boils and impetigo.", tags: ["Boil Specialist"] },
    { id: 148, name: "Clindamycin Gel", category: "Skin Care", price: 110, dose: "15g", image: "BsDropletFill", desc: "Water-based antibiotic for painful inflammatory acne.", tags: ["Acne Combat"] },
    { id: 149, name: "Ketoconazole Shampoo", category: "Skin Care", price: 340, dose: "100ml", image: "BsDropletFill", desc: "Medical shampoo for severe stubborn dandruff and flakes.", tags: ["Dandruff Hero"] },
    { id: 150, name: "Calamine Lotion 100ml", category: "Skin Care", price: 145, dose: "100ml", image: "BsDropletFill", desc: "Cooling relief for chickenpox, heat rash, and insect bites.", tags: ["User's Favorite"] },
    { id: 151, name: "Selsun Suspension", category: "Skin Care", price: 220, dose: "120ml", image: "BsDropletFill", desc: "Selenium sulfide for fungal scalp infections.", tags: ["Medical Shampoo"] },
    { id: 152, name: "Terbinafine 250", category: "Skin Care", price: 390, dose: "7 Tablets", image: "BsCapsule", desc: "Oral treatment for deep fungal nail infections.", tags: ["Nail Health"] },
    { id: 153, name: "Elocon Cream", category: "Skin Care", price: 550, dose: "15g", image: "BsDropletFill", desc: "Mometasone for severe psoriasis and allergies.", tags: ["Deep Action"] },
    { id: 154, name: "Skinlite Cream", category: "Skin Care", price: 250, dose: "20g", image: "BsDropletFill", desc: "Brightening cream for glow and dark circle reduction.", tags: ["Fairness Clinical"] },
    { id: 155, name: "Permethrin Lotion", category: "Skin Care", price: 115, dose: "60ml", image: "BsDropletFill", desc: "One-time application for scabies and lice removal.", tags: ["Lice Control"] },
    { id: 156, name: "Clobetasol Propionate", category: "Skin Care", price: 75, dose: "30g", image: "BsDropletFill", desc: "Very strong steroid for localized thick skin patches.", tags: ["Ortho-Derm"] },
    { id: 157, name: "Bimatoprost Solution", category: "Skin Care", price: 1200, dose: "3ml", image: "BsDropletFill", desc: "Promotes eyelash growth and darkening (Neural Eye Tech).", tags: ["Beauty Tech"] },
    { id: 158, name: "Sebogel Acne Gel", category: "Skin Care", price: 320, dose: "30g", image: "BsDropletFill", desc: "Salicylic acid mix for oily skin blackheads.", tags: ["Blackhead Stop"] },
    { id: 159, name: "Glycerin IP", category: "Skin Care", price: 65, dose: "100ml", image: "BsDropletFill", desc: "Pure hydration for extreme winter dry skin.", tags: ["Winter Essential"] },
    { id: 160, name: "Sunscreen Ultra SPF 50", category: "Skin Care", price: 850, dose: "100g", image: "BsDropletFill", desc: "Photo-stable protection against UVA/UVB/Blue light.", tags: ["Neural Sun Block"] },
    { id: 161, name: "Vitamin E Skin Oil", category: "Skin Care", price: 420, dose: "50ml", image: "BsDropletFill", desc: "Pure Vitamin E for scar fading and stretch marks.", tags: ["Scar Repair"] },
    { id: 162, name: "Tea Tree Oil Pure", category: "Skin Care", price: 550, dose: "15ml", image: "BsDropletFill", desc: "Natural antiseptic for localized acne spot treatment.", tags: ["Natural Detox"] },
    { id: 163, name: "Boroline Antiseptic", category: "Skin Care", price: 40, dose: "20g", image: "BsDropletFill", desc: "The legendary healer for cracked lips and dry skin.", tags: ["The Indian Classic"] },
    { id: 164, name: "Fair & Lovely Multi", category: "Skin Care", price: 110, dose: "50g", image: "BsDropletFill", desc: "Instant glow with vitamins for daily usage.", tags: ["Daily Glow"] },
    { id: 165, name: "Kojic Acid Serum", category: "Skin Care", price: 680, dose: "30ml", image: "BsDropletFill", desc: "Targeted brightening for brown spots and sun damage.", tags: ["Brightening Elite"] },
    { id: 166, name: "Neosporin Ointment", category: "Skin Care", price: 130, dose: "10g", image: "BsDropletFill", desc: "Triple antibiotic for minor cuts and abrasions.", tags: ["First Aid Hero"] },
    { id: 167, name: "Soframycin Cream", category: "Skin Care", price: 55, dose: "30g", image: "BsDropletFill", desc: "Framycetin for small burns and infected wounds.", tags: ["Burn Healer"] },
    { id: 168, name: "Clearvid Acne Wash", category: "Skin Care", price: 340, dose: "100ml", image: "BsDropletFill", desc: "Foaming cleanser with Zinc for clear complexion.", tags: ["Deep Clean"] },
    { id: 169, name: "Tacrolimus 0.1%", category: "Skin Care", price: 950, dose: "10g", image: "BsDropletFill", desc: "Non-steroid cream for stubborn sensitive eczema.", tags: ["Safe Steroid Alter"] },
    { id: 170, name: "Benzoyl Peroxide 5%", category: "Skin Care", price: 165, dose: "20g", image: "BsDropletFill", desc: "Dries up active pus-filled pimples overnight.", tags: ["Pimple Stop"] },

    // --- COUGH & COLD (20 ITEMS) ---
    { id: 171, name: "Benadryl Cough Syrup", category: "Cough & Cold", price: 145, dose: "100ml", image: "BsDropletFill", desc: "Relieves dry cough, sneezing, and runny nose.", tags: ["Night Relief"] },
    { id: 172, name: "Ascoril LS", category: "Cough & Cold", price: 115, dose: "100ml", image: "BsDropletFill", desc: "Breaks down mucus for easy breathing during chest congestion.", tags: ["Chest Expert"] },
    { id: 173, name: "Vicks Vaporub 50g", category: "Cough & Cold", price: 185, dose: "50g Jar", image: "BsDropletFill", desc: "Topical rub for relief from chest and nose congestion.", tags: ["Multi-Action Healer"] },
    { id: 174, name: "Honitus Herbal", category: "Cough & Cold", price: 95, dose: "100ml", image: "BsDropletFill", desc: "Ayurvedic honey-based syrup, safe for children.", tags: ["Non-Drowsy"] },
    { id: 175, name: "Alex Cough Lozenges", category: "Cough & Cold", price: 120, dose: "10 strips", image: "BsCapsule", desc: "Instant sore throat relief with cooling menthol.", tags: ["Pocket Handy"] },
    { id: 176, name: "Sinarest New", category: "Cough & Cold", price: 65, dose: "10 Tablets", image: "BsCapsule", desc: "Effective for cold, headache, and allergic fever.", tags: ["Cold Specialist"] },
    { id: 177, name: "Otrivin Adult Spray", category: "Cough & Cold", price: 95, dose: "10ml", image: "BsDropletFill", desc: "Unblocks nose in 25 seconds, lasts for 12 hours.", tags: ["Rapid Action"] },
    { id: 178, name: "Cheston Cold", category: "Cough & Cold", price: 45, dose: "10 Tablets", image: "BsCapsule", desc: "Affordable combination for blocked nose and sneezing.", tags: ["Value Gear"] },
    { id: 179, name: "Zyrtec 10mg", category: "Cough & Cold", price: 190, dose: "10 Tablets", image: "BsCapsule", desc: "Non-sedating antihistamine for all-day allergy relief.", tags: ["Premium Allergy"] },
    { id: 180, name: "Allegra 120mg", category: "Cough & Cold", price: 215, dose: "10 Tablets", image: "BsCapsule", desc: "Superior Fexofenadine for seasonal hay fever.", tags: ["Sports Approved"] },
    { id: 181, name: "Corex-DX Syrup", category: "Cough & Cold", price: 165, dose: "100ml", image: "BsDropletFill", desc: "Dextromethorphan for stubborn dry night coughs.", tags: ["Night Sleep"] },
    { id: 182, name: "Grilinctus Syrup", category: "Cough & Cold", price: 135, dose: "100ml", image: "BsDropletFill", desc: "Classic multi-symptom cold and cough liquid.", tags: ["The Reliable One"] },
    { id: 183, name: "Vicks Inhaler", category: "Cough & Cold", price: 60, dose: "0.5ml", image: "BsDropletFill", desc: "Instant nasal clearance in a pocket-sized stick.", tags: ["On the Go"] },
    { id: 184, name: "Halls Extra Strong", category: "Cough & Cold", price: 10, dose: "5 Lozenges", image: "BsMagic", desc: "Deep vapor action lozenges for throat irritation.", tags: ["Vapor Force"] },
    { id: 185, name: "Cebrex Cold Plus", category: "Cough & Cold", price: 85, dose: "10 Tablets", image: "BsCapsule", desc: "High-dose combination for severe flu symptoms.", tags: ["Flu Buster"] },
    { id: 186, name: "Steam Inhaler Neural", category: "Cough & Cold", price: 1250, dose: "Device", image: "BsLightningFill", desc: "Ionic steam device for deep sinus clearance.", tags: ["New Gen Device"] },
    { id: 187, name: "Karvol Plus", category: "Cough & Cold", price: 110, dose: "10 Capsules", image: "BsCapsule", desc: "Fast-acting inhalant capsules for steam use.", tags: ["Nose Opener"] },
    { id: 188, name: "Solvin Cold Syrup", category: "Cough & Cold", price: 75, dose: "60ml", image: "BsDropletFill", desc: "Child-safe liquid for cold and runny nose.", tags: ["Pediatric Choice"] },
    { id: 189, name: "Torex Herbal", category: "Cough & Cold", price: 105, dose: "100ml", image: "BsDropletFill", desc: "Tulsi and Vasaka based clean syrup.", tags: ["No Alcohol"] },
    { id: 190, name: "Nasoclear Mist", category: "Cough & Cold", price: 65, dose: "20ml", image: "BsDropletFill", desc: "Saline nasal spray for natural nose cleaning.", tags: ["All Natural"] },

    // --- MUSCLE CARE (10 ITEMS) ---
    { id: 191, name: "Skelaxin 800mg", category: "Muscle Care", price: 1450, dose: "10 Tablets", image: "BsCapsule", desc: "Potent muscle relaxant for severe spasms and injury.", tags: ["Neural Relaxant"] },
    { id: 192, name: "Cyclobenzaprine 10", category: "Muscle Care", price: 820, dose: "15 Tablets", image: "BsCapsule", desc: "Relieves muscle spasms associated with acute conditions.", tags: ["Deep Relax"] },
    { id: 193, name: "Myoril 4mg", category: "Muscle Care", price: 290, dose: "10 Capsules", image: "BsCapsule", desc: "Thiocolchicoside for quick post-workout recovery.", tags: ["Sports Choice"] },
    { id: 194, name: "Bakson's Rheum Aid", category: "Muscle Care", price: 195, dose: "30 Tablets", image: "BsCapsule", desc: "Homeopathic relief for joint stiffness and muscle fatigue.", tags: ["Gentle Healing"] },
    { id: 195, name: "Himalaya Rumalaya Gel", category: "Muscle Care", price: 140, dose: "30g", image: "BsDropletFill", desc: "Herbal anti-inflammatory gel for orthopedic pain.", tags: ["Herb Healer"] },
    { id: 196, name: "Neuro-Muscular Patch", category: "Muscle Care", price: 450, dose: "3 Patches", image: "BsMagic", desc: "8-hour heat patch for focal muscle knot relief.", tags: ["Modern Tech"] },
    { id: 197, name: "Orthopedic Knee Support", category: "Muscle Care", price: 850, dose: "1 Unit", image: "BsShieldCheck", desc: "Premium stability gear for weak knee joints.", tags: ["Support Gear"] },
    { id: 198, name: "Compression Bandage", category: "Muscle Care", price: 120, dose: "10cm x 4m", image: "BsActivity", desc: "High-stretch crepe bandage for sprains and swellings.", tags: ["Essential Aid"] },
    { id: 199, name: "Epsom Salt Ultra", category: "Muscle Care", price: 280, dose: "500g", image: "BsDropletFill", desc: "Magnesium sulfate soak for global muscle relaxation.", tags: ["Body Spa"] },
    { id: 200, name: "TENS Unit Mini", category: "Muscle Care", price: 2400, dose: "Device", image: "BsLightningFill", desc: "Electric pulse therapy for chronic muscle pain.", tags: ["Physio Grade"] },

    // --- PEDIATRIC CARE (60 ITEMS) ---
    { id: 201, name: "Calpol 250 Syrup", category: "Pediatric Care", price: 45, dose: "60ml", image: "BsDropletFill", desc: "Strawberry flavored fever and pain relief for children.", tags: ["Kid's Choice"] },
    { id: 202, name: "Meftal P Drops", category: "Pediatric Care", price: 65, dose: "15ml", image: "BsDropletFill", desc: "Fast-acting fever reducer for infants and toddlers.", tags: ["High Heat"] },
    { id: 203, name: "Colicaid Drops", category: "Pediatric Care", price: 85, dose: "15ml", image: "BsDropletFill", desc: "Relieves infant colic, gas, and abdominal bloating.", tags: ["Anti-Colic"] },
    { id: 204, name: "Taxim-O 50 Syrup", category: "Pediatric Care", price: 110, dose: "30ml", image: "BsDropletFill", desc: "Pediatric antibiotic for ear and throat infections.", tags: ["Prescription Required"] },
    { id: 205, name: "Zincovit Drops", category: "Pediatric Care", price: 65, dose: "15ml", image: "BsDropletFill", desc: "Essential multi-mineral multivitamin drops for infants.", tags: ["Growth Boost"] },
    { id: 206, name: "Bonnisan Syrup", category: "Pediatric Care", price: 110, dose: "200ml", image: "BsDropletFill", desc: "Digestive tonic for baby's healthy growth.", tags: ["Traditional"] },
    { id: 207, name: "Pudin Hara Liquid Child", category: "Pediatric Care", price: 40, dose: "10ml", image: "BsDropletFill", desc: "Pure Ayurvedic gas relief for children.", tags: ["Natural"] },
    { id: 208, name: "Enterogermina 2B", category: "Pediatric Care", price: 65, dose: "5ml Bottle", image: "BsDropletFill", desc: "Instant probiotic for childhood diarrhea recovery.", tags: ["Tasteless"] },
    { id: 209, name: "Mox Junior Tab", category: "Pediatric Care", price: 45, dose: "10 Tablets", image: "BsCapsule", desc: "Soluble pediatric antibiotic for easy intake.", tags: ["Child Safe"] },
    { id: 210, name: "Kidicare Elixir Plus", category: "Pediatric Care", price: 180, dose: "200ml", image: "BsDropletFill", desc: "Calcium and growth factors for growing children.", tags: ["Strong Bones"] },
    { id: 211, name: "Ondem Syrup child", category: "Pediatric Care", price: 45, dose: "30ml", image: "BsDropletFill", desc: "Stops vomiting and nausea in children fast.", tags: ["Anti-Vomit"] },
    { id: 212, name: "Augmentin DDS", category: "Pediatric Care", price: 155, dose: "30ml", image: "BsDropletFill", desc: "High-strength pediatric antibiotic for resistant germs.", tags: ["Clinical Grade"] },
    { id: 213, name: "Vizylac Pediatric", category: "Pediatric Care", price: 40, dose: "10 Sachets", image: "BsMagic", desc: "Pre-probiotic mix to fix childhood gut health.", tags: ["Gut Health"] },
    { id: 214, name: "T-Bact Cream Mini", category: "Pediatric Care", price: 290, dose: "5g", image: "BsDropletFill", desc: "Antibiotic ointment for school-age skin scratches.", tags: ["Wound Care"] },
    { id: 215, name: "Gripe Water Alcohol Free", category: "Pediatric Care", price: 65, dose: "150ml", image: "BsDropletFill", desc: "Classic safe formula for infant hiccups and gas.", tags: ["Safe Original"] },

    // --- EYE & ENT CARE (40 ITEMS) ---
    { id: 250, name: "Refresh Tears 10ml", category: "Eye & ENT", price: 295, dose: "10ml", image: "BsDropletFill", desc: "Artificial tears for dry eyes and computer strain.", tags: ["No. 1 Recommended"] },
    { id: 251, name: "Ciplox Eye/Ear Drops", category: "Eye & ENT", price: 35, dose: "10ml", image: "BsDropletFill", desc: "Antiseptic drops for pink eye and ear infections.", tags: ["Value Pack"] },
    { id: 252, name: "Otrivin Pediatric Spray", category: "Eye & ENT", price: 85, dose: "10ml", image: "BsDropletFill", desc: "Safe nasal clearance for babies and children.", tags: ["Gentle Flow"] },
    { id: 253, name: "Candibiotic Ear Drop", category: "Eye & ENT", price: 85, dose: "5ml", image: "BsDropletFill", desc: "Triple action relief for painful ear infections.", tags: ["Pain Relief"] },
    { id: 254, name: "Vicks Inhaler Stick", category: "Eye & ENT", price: 65, dose: "0.5ml", image: "BsDropletFill", desc: "Menthol stick for instant nose clearance on the go.", tags: ["Pocket Hero"] },
    { id: 255, name: "Clearline Eye Drops", category: "Eye & ENT", price: 65, dose: "10ml", image: "BsDropletFill", desc: "Removes redness and itching in seconds.", tags: ["Instant Bright"] },
    { id: 256, name: "Soluwax Ear Drops", category: "Eye & ENT", price: 45, dose: "10ml", image: "BsDropletFill", desc: "Softens hardened ear wax for easy removal.", tags: ["Wax Softener"] },
    { id: 257, name: "Betnovate-N Ear Drop", category: "Eye & ENT", price: 55, dose: "5ml", image: "BsDropletFill", desc: "Antibacterial steroid for inner ear inflammation.", tags: ["ENT Choice"] },
    { id: 258, name: "Moistane Dry Eye", category: "Eye & ENT", price: 280, dose: "10ml", image: "BsDropletFill", desc: "Long-lasting lubrication for modern digital users.", tags: ["Digital Hub"] },
    { id: 259, name: "Eyerest Night Gel", category: "Eye & ENT", price: 420, dose: "10g", image: "BsDropletFill", desc: "Deep hydration gel for overnight dry eye repair.", tags: ["Night Repair"] },

    // --- DENTAL CARE (30 ITEMS) ---
    { id: 300, name: "Zytee Mouth Gel", category: "Dental Care", price: 85, dose: "10g", image: "BsDropletFill", desc: "Instant numbing for mouth ulcers and gum pain.", tags: ["Ulcer Stop"] },
    { id: 301, name: "Clohex Mouthwash", category: "Dental Care", price: 110, dose: "150ml", image: "BsDropletFill", desc: "Antiseptic wash for gingivitis and bad breath.", tags: ["Bad Breath Kill"] },
    { id: 302, name: "Sensodyne Rapid Relief", category: "Dental Care", price: 145, dose: "80g", image: "BsDropletFill", desc: "Works within 60 seconds for sensitive tooth pain.", tags: ["Clinically Proven"] },
    { id: 303, name: "Metrogyl DG Gel", category: "Dental Care", price: 45, dose: "20g", image: "BsDropletFill", desc: "Antibacterial gel for bleeding gums and infections.", tags: ["Gum Health"] },
    { id: 304, name: "Clove Oil Liquid", category: "Dental Care", price: 65, dose: "2ml", image: "BsDropletFill", desc: "Concentrated clove oil for emergency toothache.", tags: ["Natural Numb"] },
    { id: 305, name: "Zandu Red Paste", category: "Dental Care", price: 110, dose: "150g", image: "BsDropletFill", desc: "Ayurvedic toothpaste with cloves and mint power.", tags: ["Traditional Clean"] },
    { id: 306, name: "Thermoseal RA", category: "Dental Care", price: 165, dose: "100g", image: "BsDropletFill", desc: "Re-mineralizing paste for enamel protection.", tags: ["Enamel Care"] },
    { id: 307, name: "Listerine Total Care", category: "Dental Care", price: 280, dose: "250ml", image: "BsDropletFill", desc: "6-in-1 mouthwash for complete oral hygiene.", tags: ["Global Choice"] },

    // --- AYURVEDIC & HERBAL (EXPANDED) (50 ITEMS) ---
    { id: 350, name: "Triphala Churna Purified", category: "Ayurvedic", price: 195, dose: "100g", image: "BsMagic", desc: "Powerful detoxifier for colon and eye health.", tags: ["Detox Hero"] },
    { id: 351, name: "Liv-52 DS Tablets", category: "Ayurvedic", price: 110, dose: "60 Tablets", image: "BsCapsule", desc: "Double-strength liver protection and appetite booster.", tags: ["Liver Guard"] },
    { id: 352, name: "Shilajit Gold Resin", category: "Ayurvedic", price: 950, dose: "20g", image: "BsDropletFill", desc: "Purified Himalayan resin for stamina and vitality.", tags: ["Energy King"] },
    { id: 353, name: "Himalaya Cystone", category: "Ayurvedic", price: 135, dose: "60 Tablets", image: "BsCapsule", desc: "Ayurvedic formula to dissolve kidney stones and clear UTI.", tags: ["Stone Eraser"] },
    { id: 354, name: "Safed Musli Vital", category: "Ayurvedic", price: 420, dose: "60 Capsules", image: "BsCapsule", desc: "Natural adaptogen for physical strength and rejuvenation.", tags: ["Vitality Boost"] },
    { id: 355, name: "Brahmi Vati Gold", category: "Ayurvedic", price: 290, dose: "30 Tablets", image: "BsCapsule", desc: "Brain tonic for memory, focus, and exam-stress relief.", tags: ["Brain Gold"] },
    { id: 356, name: "Neem Purifier Caps", category: "Ayurvedic", price: 120, dose: "60 Capsules", image: "BsCapsule", desc: "Internal blood cleanser for acne-free glowing skin.", tags: ["Pimple Free"] },
    { id: 357, name: "Shatavari Granules", category: "Ayurvedic", price: 340, dose: "200g", image: "BsDropletFill", desc: "Hormonal balance and lactation support for women.", tags: ["Women's Health"] },
    { id: 358, name: "Giloy Ghanvati Tablet", category: "Ayurvedic", price: 65, dose: "60 Tablets", image: "BsCapsule", desc: "Platelet booster and chronic fever management.", tags: ["Immunity Expert"] },
    { id: 359, name: "Abhayarishta Liquid", category: "Ayurvedic", price: 165, dose: "450ml", image: "BsDropletFill", desc: "Fermented herbal tonic for piles and constipation.", tags: ["Piles Relief"] },

    // --- SURGICAL & FIRST AID SUPPLIES (50 ITEMS) ---
    { id: 400, name: "Digital Thermometer Neural", category: "Surgical", price: 450, dose: "1 Unit", image: "BsLightningFill", desc: "High-precision digital fever reading with memory.", tags: ["Home Essential"] },
    { id: 401, name: "Omron BP Monitor", category: "Surgical", price: 2850, dose: "Device", image: "BsHeartPulseFill", desc: "Clinical accuracy automated blood pressure monitor.", tags: ["Heart Health"] },
    { id: 402, name: "Pulse Oximeter Pro", category: "Surgical", price: 1250, dose: "Device", image: "BsActivity", desc: "Instant SpO2 and pulse rate monitoring.", tags: ["COVID Safe"] },
    { id: 403, name: "Nebulizer Machine Elite", category: "Surgical", price: 3500, dose: "Device", image: "BsLightningFill", desc: "Heavy-duty compressor for asthma and cold treatments.", tags: ["Lungs Care"] },
    { id: 404, name: "Glucometer G-Touch", category: "Surgical", price: 950, dose: "Kit", image: "BsActivity", desc: "Smart sugar testing kit with 10 free strips.", tags: ["Diabetes Guard"] },
    { id: 405, name: "N95 Mask Pro-Shield", category: "Surgical", price: 150, dose: "Pack of 5", image: "BsShieldCheck", desc: "High-filtration breathable protection.", tags: ["Virus Shield"] },
    { id: 406, name: "Sterile Crepe Bandage", category: "Surgical", price: 85, dose: "1 Unit", image: "BsActivity", desc: "Elastic support for sprains and joint injuries.", tags: ["First Aid"] },
    { id: 407, name: "Infrared Thermometer", category: "Surgical", price: 1850, dose: "Device", image: "BsLightningFill", desc: "Non-contact rapid temperature screening.", tags: ["Clinical Grade"] },
    { id: 408, name: "Hot Water Bag Electric", category: "Surgical", price: 420, dose: "1 Unit", image: "BsLightningFill", desc: "Instant heat for muscle pain and cramps.", tags: ["Pain Combo"] },
    { id: 409, name: "Vaporizer 3-in-1", category: "Surgical", price: 350, dose: "Device", image: "BsLightningFill", desc: "Steam inhaler for face, nose, and throat.", tags: ["Winter Hero"] },

    // --- SPECIALIZED CHRONIC CARE (50 ITEMS) ---
    { id: 450, name: "Imatinib 400mg", category: "Chronic Care", price: 9500, dose: "10 Tablets", image: "BsCapsule", desc: "Targeted therapy for chronic myeloid leukemia.", tags: ["Life Saving", "Specialist Link"] },
    { id: 451, name: "Letrozole Clinical", category: "Chronic Care", price: 185, dose: "5 Tablets", image: "BsCapsule", desc: "Advanced infertility and hormone sensitive therapy.", tags: ["Fertility Care"] },
    { id: 452, name: "Azathioprine 50mg", category: "Chronic Care", price: 450, dose: "10 Tablets", image: "BsCapsule", desc: "Immune system balancer for autoimmune conditions.", tags: ["Autoimmune"] },
    { id: 453, name: "Mestinon 60mg", category: "Chronic Care", price: 1850, dose: "150 Tablets", image: "BsCapsule", desc: "Nerve-muscle communication for Myasthenia Gravis.", tags: ["Neuro Specialist"] },
    { id: 454, name: "Desmopressin Spray", category: "Chronic Care", price: 1450, dose: "5ml", image: "BsDropletFill", desc: "Hormonal spray for water balance and bedwetting.", tags: ["Kidney Care"] },

    // --- RARE SURGICAL & SPECIALIZED (60+ ITEMS to reach 515) ---
    { id: 455, name: "Heparin Injection Clinical", category: "Surgical", price: 1250, dose: "5ml", image: "BsDropletFill", desc: "Hospital grade blood thinner for stroke prevention.", tags: ["Critical Care"] },
    { id: 456, name: "Midazolam 5mg/ml", category: "Surgical", price: 340, dose: "2ml", image: "BsDropletFill", desc: "Pre-surgical sedation for anxiety and amnesia.", tags: ["Restricted"] },
    { id: 457, name: "Dobutamine Infusion", category: "Surgical", price: 4500, dose: "50ml", image: "BsDropletFill", desc: "ICU heart pump support for acute shock.", tags: ["Heart Support"] },
    { id: 458, name: "Lignocaine 2% Gel Pro", category: "Surgical", price: 45, dose: "30g", image: "BsDropletFill", desc: "Surface anesthesia for minor clinical procedures.", tags: ["Local Numb"] },
    { id: 459, name: "Adapalene + BP Gel", category: "Skin Care", price: 1200, dose: "20g", image: "BsDropletFill", desc: "Double action acne blast for adult cystic acne.", tags: ["Dermatologist Plus"] },
    { id: 460, name: "Coal Tar Scalp Solution", category: "Skin Care", price: 340, dose: "100ml", image: "BsDropletFill", desc: "Medical solution for severe scalp psoriasis scaling.", tags: ["Psoriasis Cure"] },
    { id: 461, name: "Minoxidil 5% Topical", category: "Skin Care", price: 850, dose: "60ml", image: "BsDropletFill", desc: "Proven hair regrowth formula for male pattern baldness.", tags: ["Hair Growth"] },
    { id: 462, name: "Azelaic Acid 20% Pro", category: "Skin Care", price: 650, dose: "15g", image: "BsDropletFill", desc: "Clears pigmentation and rosacea for even skin tone.", tags: ["Tone Fixer"] },
    { id: 463, name: "Emla Numbing Cream", category: "Surgical", price: 450, dose: "5g", image: "BsDropletFill", desc: "Total skin numbing for painless injections.", tags: ["Painless Tech"] },
    { id: 464, name: "Betadine Gargle Mint", category: "Eye & ENT", price: 180, dose: "100ml", image: "BsDropletFill", desc: "Infection clearing gargle for severe sore throat.", tags: ["Gargle Expert"] },
    { id: 465, name: "Melatonin Sleep Gummy", category: "Wellness", price: 1100, dose: "30 Gummies", image: "BsMagic", desc: "Friendly sleep support for restless nights.", tags: ["Best Seller"] },
    { id: 466, name: "Tulsi Green Tea Organic", category: "Wellness", price: 180, dose: "25 Tea Bags", image: "BsMagic", desc: "Antioxidant rich blend for immunity and stress.", tags: ["Healthy Tea"] },
    { id: 467, name: "Isobag Fiber", category: "Wellness", price: 145, dose: "100g", image: "BsMagic", desc: "Natural fiber supplement for smooth morning motions.", tags: ["Fiber Plus"] },
    { id: 468, name: "Amrutanjan Advanced Balm", category: "Pain Relief", price: 40, dose: "10g", image: "BsDropletFill", desc: "Legendary pain relief balm for headache and muscle.", tags: ["The Indian Healer"] },
    { id: 469, name: "Activated Charcoal Caps", category: "Wellness", price: 110, dose: "30 Capsules", image: "BsCapsule", desc: "Natural detox for gas and bloating.", tags: ["Digestive Detox"] },
    { id: 470, name: "Solvin Cold Drops child", category: "Pediatric Care", price: 75, dose: "15ml", image: "BsDropletFill", desc: "Nose and throat relief for infants with cold.", tags: ["Pediatric Choice"] },
    { id: 471, name: "Electral Energy Pack", category: "Wellness", price: 20, dose: "Sachet", image: "BsMagic", desc: "Instant hydration and energy restoration.", tags: ["Energy Burst"] },
    { id: 472, name: "Ondansetron MD Tab", category: "Pain Relief", price: 65, dose: "10 Tablets", image: "BsCapsule", desc: "Mouth-melt tabs for instant nausea control.", tags: ["Fast Action"] },
    { id: 473, name: "Clotrimazole Dusting Powder Pro", category: "Skin Care", price: 110, dose: "100g", image: "BsMagic", desc: "Keeps skin folds dry and fungal free.", tags: ["Summer Essential"] },
    { id: 474, name: "Homeo Arnica Pain Gel", category: "Pain Relief", price: 120, dose: "30g", image: "BsDropletFill", desc: "Gentle healing for bruises and sprains.", tags: ["Natural Heal"] },
    { id: 475, name: "Vicks Steam Inhaler Device", category: "Surgical", price: 65, dose: "Device", image: "BsLightningFill", desc: "Portable steam stick for easy breathing.", tags: ["Breathe Easy"] },
    { id: 476, name: "Moist Lip SPF Balm", category: "Skin Care", price: 180, dose: "1 Unit", image: "BsDropletFill", desc: "Protects and heals dry lips from sun damage.", tags: ["Lip Care"] },

    // --- FINAL ULTRA ENTRIES (500+ MILESTONE) ---
    { id: 477, name: "Digital Oximeter Pro-X", category: "Surgical", price: 1450, dose: "Device", image: "BsActivity", desc: "Advanced SpO2 sensor for athletes and heart patients.", tags: ["Elite Gear"] },
    { id: 478, name: "Compression Stockings (Pair)", category: "Surgical", price: 950, dose: "Pair", image: "BsShieldCheck", desc: "Medical grade compression for varicose veins and edema.", tags: ["Vein Care"] },
    { id: 479, name: "Walker with Wheels Pro", category: "Surgical", price: 4500, dose: "Unit", image: "BsShieldCheck", desc: "Superior mobility support for geriatric recovery.", tags: ["Mobility Elite"] },
    { id: 480, name: "Folding Wheelchair Classic", category: "Surgical", price: 9200, dose: "Unit", image: "BsShieldCheck", desc: "Lightweight durable wheelchair for daily travel.", tags: ["Accessibility"] },
    { id: 481, name: "Back Support Belt Pro", category: "Surgical", price: 1250, dose: "Unit", image: "BsShieldCheck", desc: "Adjustable lumbar support for disk bulge and sprains.", tags: ["Ortho Support"] },
    { id: 482, name: "Cervical Collar Soft", category: "Surgical", price: 450, dose: "Unit", image: "BsShieldCheck", desc: "Relieves neck pain and stabilizes cervical spine.", tags: ["Neck Care"] },
    { id: 483, name: "Wrist Splint Elite", category: "Surgical", price: 650, dose: "Unit", image: "BsShieldCheck", desc: "Supports carpal tunnel and wrist sprains.", tags: ["Joint Support"] },
    { id: 484, name: "Elbow Support Breathable", category: "Surgical", price: 340, dose: "Unit", image: "BsShieldCheck", desc: "Compression for tennis elbow and joint strain.", tags: ["Sports Plus"] },
    { id: 485, name: "Ankle Binder Elastic", category: "Surgical", price: 280, dose: "Unit", image: "BsShieldCheck", desc: "Stable support for weak ankles and twists.", tags: ["Recovery"] },
    { id: 486, name: "Post-Op Shoe Universal", category: "Surgical", price: 850, dose: "Pair", image: "BsShieldCheck", desc: "Protective footwear for after foot surgery or injury.", tags: ["Surgery Care"] },
    { id: 487, name: "Surgical Scalpel Set (Sterile)", category: "Surgical", price: 120, dose: "5 Units", image: "BsDropletFill", desc: "Disposable sterile blades for minor dressings/surgeries.", tags: ["Clinical Only"] },
    { id: 488, name: "Forceps Multi-Purpose", category: "Surgical", price: 340, dose: "1 Unit", image: "BsLightningFill", desc: "Stainless steel forceps for clinical dressing use.", tags: ["Medical Grade"] },
    { id: 489, name: "Surgical Scissors Sharp", category: "Surgical", price: 165, dose: "1 Unit", image: "BsLightningFill", desc: "High-grade cutting gear for clinical dressings.", tags: ["Clinic Standard"] },
    { id: 490, name: "Spirit Swabs (Sterile)", category: "Surgical", price: 220, dose: "100 Units", image: "BsDropletFill", desc: "Pre-injection alcohol swabs for instant disinfection.", tags: ["Hygiene Hero"] },
    { id: 491, name: "Cotton Roll 400g Pure", category: "Surgical", price: 180, dose: "Pack", image: "BsDropletFill", desc: "Absorbent hospital grade cotton for large dressings.", tags: ["Essential Stock"] },
    { id: 492, name: "Abdominal Belt 9-inch", category: "Surgical", price: 550, dose: "Unit", image: "BsShieldCheck", desc: "Supports abdominal wall post-surgery or pregnancy.", tags: ["Recovery Care"] },
    { id: 493, name: "Ear Syringe Rubber", category: "Surgical", price: 85, dose: "Unit", image: "BsDropletFill", desc: "Gentle suction for ear wax flushing/cleaning.", tags: ["ENT Aid"] },
    { id: 494, name: "Nasal Aspirator (Baby)", category: "Surgical", price: 145, dose: "Unit", image: "BsDropletFill", desc: "Safely clears baby's nose for easy breathing.", tags: ["Parenting Choice"] },
    { id: 495, name: "Condoms Ultra Thin (10s)", category: "Surgical", price: 155, dose: "Pack", image: "BsShieldCheck", desc: "High sensitivity protection for safe wellness.", tags: ["Safety First"] },
    { id: 496, name: "Pregnancy Test Kit (Elite)", category: "Surgical", price: 95, dose: "1 Test", image: "BsActivity", desc: "99% accurate instant detection in 3 mins.", tags: ["Instant Results"] },
    { id: 497, name: "Ovulation Tracker Strips", category: "Surgical", price: 420, dose: "5 Tests", image: "BsActivity", desc: "Identifies fertility windows for family planning.", tags: ["Family Wellness"] },
    { id: 498, name: "Lubricating Jelly 100g", category: "Surgical", price: 180, dose: "Tube", image: "BsDropletFill", desc: "Sterile non-greasy jelly for clinical procedures.", tags: ["Clinical Grade"] },
    { id: 499, name: "Blood Glucose Lancets", category: "Surgical", price: 250, dose: "100 Units", image: "BsLightningFill", desc: "Ultra-thin needles for painless sugar testing.", tags: ["Painless Test"] },
    { id: 500, name: "Insulin Needle 31G", category: "Surgical", price: 450, dose: "Pack of 10", image: "BsLightningFill", desc: "Smallest pain-free insulin delivery needles.", tags: ["Diabetes Care"] },
    { id: 501, name: "Stethoscope Professional", category: "Surgical", price: 4200, dose: "Device", image: "BsHeartPulseFill", desc: "High acoustic sensitivity for clinical auscultation.", tags: ["Doctor Choice"] },
    { id: 502, name: "Infrared Heat Lamp", category: "Surgical", price: 2100, dose: "Device", image: "BsLightningFill", desc: "Deep penetrating heat for severe chronic joint pain.", tags: ["Physio Grade"] },
    { id: 503, name: "Kinesiology Tape (Roll)", category: "Surgical", price: 340, dose: "1 Roll", image: "BsActivity", desc: "Supports muscles and joints without limiting motion.", tags: ["Sports Tech"] },
    { id: 504, name: "Epsom Salt Crystal Pro", category: "Wellness", price: 110, dose: "200g", image: "BsMagic", desc: "Pure bath salts for rapid muscle detox and relaxation.", tags: ["Body Care"] },
    { id: 505, name: "B Complex Oral Drops", category: "Pediatric Care", price: 45, dose: "15ml", image: "BsDropletFill", desc: "Vitamins to fix mouth ulcers and improve feed in babies.", tags: ["Vitality Drops"] },
    { id: 506, name: "Gripe Water Cherry Flav", category: "Pediatric Care", price: 85, dose: "120ml", image: "BsDropletFill", desc: "Advanced colic relief with tasty cherry flavor.", tags: ["Happy Baby"] }
];
